#!/usr/bin/env bash
# GENERATED by tools/render_agent_surfaces.py — edit the renderer, not this file.
# Escapement always-on rules injection (SessionStart).
set -uo pipefail
RULES_DIR="${CLAUDE_PLUGIN_ROOT:-$(cd "$(dirname "$0")/.." && pwd)}/rules"
python3 - "$RULES_DIR" <<'PY'
import glob, json, os, sys

rules_dir = sys.argv[1]
files = sorted(glob.glob(os.path.join(rules_dir, "*.md")))
if not files:
    ctx = (
        "[escapement] WARNING: rules bundle not found at %s. Escapement discipline "
        "rules were NOT injected this session — the plugin install may be incomplete. "
        "Reinstall/update the escapement plugin." % rules_dir
    )
else:
    parts = [
        "IMPORTANT — Escapement workflow rules (always-on, injected at session "
        "start). These instructions OVERRIDE default behavior and you MUST follow "
        "them exactly:\n"
    ]
    for f in files:
        try:
            parts.append(open(f, encoding="utf-8").read())
        except OSError as exc:
            parts.append("[escapement] WARNING: could not read %s (%s)" % (f, exc))
    ctx = "\n\n".join(parts)
print(json.dumps({
    "hookSpecificOutput": {
        "hookEventName": "SessionStart",
        "additionalContext": ctx,
    }
}))
PY
