#!/usr/bin/env python3
"""Project named-slot canonical OpenSpec bodies into per-host surfaces.

The canonical bodies live at ``agent-surfaces/openspec/<op>.md`` (read-only
input; no host reads them, the renderer never writes them). Each canon file
carries a YAML frontmatter block declaring, per op:

- ``slots``    — slot name -> per-host variant text
- ``targets``  — host -> output path (write-only; never an input dir)
- ``frontmatter`` — host -> ordered key/value pairs emitted as the surface's
  own YAML frontmatter

The body is the union of the shared steps with ``{{slot:NAME}}`` placeholders
where a step diverges by host. Projection substitutes each placeholder with the
host's variant, so a host-forbidden token (e.g. ``subagent_type`` on Codex) is
never emitted into that host's surface — selection at the slot, not post-hoc
stripping.

Slots are matched by NAME, not by line position, so an upstream restructure that
reorders or renumbers the shared steps still lands each variant correctly.
"""

from __future__ import annotations

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

# Canon source dir (read-only input). No host reads it; the renderer never
# writes into it — this is what resolves the data-flow inversion: canon is
# input-only, host surfaces are output-only, no dir is both.
CANON_DIR = Path("agent-surfaces/openspec")

GENERATED_HEADER = (
    "<!-- Generated by tools/render_agent_surfaces.py from "
    "agent-surfaces/openspec/<op>.md; edit the canon, not this file. -->"
)

_SLOT_RE = re.compile(r"\{\{slot:([A-Za-z0-9_]+)\}\}")


class ProjectionError(Exception):
    """Raised when a canon file is malformed or a slot cannot be resolved."""


def _split_frontmatter(text: str) -> tuple[str, str]:
    """Return (frontmatter_block, body) for a ``---`` fenced document."""
    lines = text.splitlines()
    if not lines or lines[0].strip() != "---":
        raise ProjectionError("canon file missing leading '---' frontmatter fence")
    for idx in range(1, len(lines)):
        if lines[idx].strip() == "---":
            fm = "\n".join(lines[1:idx])
            body = "\n".join(lines[idx + 1 :])
            return fm, body
    raise ProjectionError("canon file missing closing '---' frontmatter fence")


def _indent(line: str) -> int:
    return len(line) - len(line.lstrip(" "))


def _strip_value(raw: str) -> str:
    """Strip a scalar's surrounding quotes and unescape a double-quoted scalar.

    A double-quoted scalar may contain ``\\"`` (an embedded double quote) and
    ``\\\\`` (a literal backslash); both are unescaped so the projected surface
    carries real quotes, e.g. ``subagent_type: "general-purpose"``. A
    single-quoted scalar is taken literally (no escape processing), matching
    YAML's single-quote semantics.
    """
    value = raw.strip()
    if len(value) >= 2 and value[0] == value[-1] and value[0] == '"':
        inner = value[1:-1]
        return inner.replace('\\"', '"').replace("\\\\", "\\")
    if len(value) >= 2 and value[0] == value[-1] and value[0] == "'":
        return value[1:-1]
    return value


def parse_canon(text: str) -> dict:
    """Parse a canon document into a structured dict.

    Returns a dict with keys ``op``, ``slots`` (name -> host -> text),
    ``targets`` (host -> path), ``frontmatter`` (host -> ordered list of
    (key, value)), and ``body`` (the markdown body with slot placeholders).
    """
    fm_text, body = _split_frontmatter(text)
    op: str | None = None
    slots: dict[str, dict[str, str]] = {}
    targets: dict[str, str] = {}
    frontmatter: dict[str, list[tuple[str, str]]] = {}

    section: str | None = None  # "slots" | "targets" | "frontmatter"
    cur_slot: str | None = None  # within slots: the slot name (2-indent key)
    cur_host: str | None = None  # within frontmatter: the host (2-indent key)
    cur_nested: list | None = None  # within frontmatter: an open nested map (e.g. metadata)

    for raw in fm_text.splitlines():
        if not raw.strip():
            continue
        indent = _indent(raw)
        stripped = raw.strip()
        if ":" not in stripped:
            raise ProjectionError(f"canon frontmatter line missing ':' -> {raw!r}")
        key, _, val = stripped.partition(":")
        key = key.strip()
        val = val.strip()

        if indent == 0:
            if key == "op":
                op = _strip_value(val)
                section = None
            elif key in ("slots", "targets", "frontmatter"):
                section = key
                cur_slot = None
                cur_host = None
            else:
                raise ProjectionError(f"unknown top-level canon key: {key!r}")
            continue

        if section == "slots":
            if indent == 2:
                cur_slot = key
                slots[cur_slot] = {}
            elif indent == 4:
                if cur_slot is None:
                    raise ProjectionError("slot host entry before any slot name")
                slots[cur_slot][key] = _strip_value(val)
            else:
                raise ProjectionError(f"unexpected indent in slots: {raw!r}")
        elif section == "targets":
            if indent == 2:
                targets[key] = _strip_value(val)
            else:
                raise ProjectionError(f"unexpected indent in targets: {raw!r}")
        elif section == "frontmatter":
            if indent == 2:
                cur_host = key
                cur_nested = None
                frontmatter[cur_host] = []
            elif indent == 4:
                if cur_host is None:
                    raise ProjectionError("frontmatter key before any host")
                if val == "":
                    # Opens a nested map (e.g. `metadata:`); 6-indent lines fill it.
                    cur_nested = []
                    frontmatter[cur_host].append((key, cur_nested))
                else:
                    cur_nested = None
                    frontmatter[cur_host].append((key, _strip_value(val)))
            elif indent == 6:
                if cur_nested is None:
                    raise ProjectionError(
                        f"6-indent frontmatter line outside a nested map: {raw!r}"
                    )
                cur_nested.append((key, _strip_value(val)))
            else:
                raise ProjectionError(f"unexpected indent in frontmatter: {raw!r}")
        else:
            raise ProjectionError(f"canon frontmatter line outside a section: {raw!r}")

    if op is None:
        raise ProjectionError("canon frontmatter missing 'op'")
    return {
        "op": op,
        "slots": slots,
        "targets": targets,
        "frontmatter": frontmatter,
        "body": body,
    }


def _emit_frontmatter(pairs: list[tuple[str, str]]) -> str:
    """Emit an ordered YAML frontmatter block from explicit (key, value) pairs.

    Ordering is taken verbatim from the canon (an explicit ordered template),
    so re-render is byte-stable rather than depending on dict iteration order.
    """
    lines = ["---"]
    for key, value in pairs:
        if isinstance(value, list):
            # Nested map (e.g. metadata: author/version/generatedBy).
            lines.append(f"{key}:")
            for subkey, subval in value:
                lines.append(f'  {subkey}: "{subval}"')
        elif value.startswith("[") and value.endswith("]"):
            # tags is an inline list literal in the source surfaces; emit unquoted.
            lines.append(f"{key}: {value}")
        else:
            lines.append(f'{key}: "{value}"')
    lines.append("---")
    return "\n".join(lines)


def project_op(canon_text: str, host: str) -> str:
    """Project a parsed canon document into one host's surface text.

    Substitutes every ``{{slot:NAME}}`` with that host's variant. A slot with
    no variant for ``host`` is an error (fail closed — never emit the raw
    placeholder or another host's text).
    """
    parsed = parse_canon(canon_text)
    if host not in parsed["frontmatter"]:
        raise ProjectionError(f"canon has no frontmatter for host {host!r}")

    def _sub(match: re.Match[str]) -> str:
        name = match.group(1)
        variants = parsed["slots"].get(name)
        if variants is None:
            raise ProjectionError(f"unknown slot referenced in body: {name!r}")
        if host not in variants:
            raise ProjectionError(f"slot {name!r} has no variant for host {host!r}")
        return variants[host]

    body = _SLOT_RE.sub(_sub, parsed["body"])
    # Guard: no unresolved placeholders survived (fail closed).
    leftover = _SLOT_RE.search(body)
    if leftover is not None:
        raise ProjectionError(f"unresolved slot after projection: {leftover.group(0)}")

    fm = _emit_frontmatter(parsed["frontmatter"][host])
    body = body.strip("\n")
    return f"{fm}\n\n{body}\n"


def projection_targets(root: Path) -> dict[Path, str]:
    """Map every host target path -> rendered content across all canon ops.

    Canon dir is input-only; the returned paths are the write-only host
    surfaces. Used to wire projection into the render / --check flow.
    """
    targets: dict[Path, str] = {}
    canon_dir = root / CANON_DIR
    for canon_path in sorted(canon_dir.glob("*.md")):
        canon_text = canon_path.read_text(encoding="utf-8")
        parsed = parse_canon(canon_text)
        for host, rel_target in parsed["targets"].items():
            content = project_op(canon_text, host)
            targets[root / rel_target] = content
    return targets
