#!/usr/bin/env python3
"""Render and check host-specific agent surfaces from a neutral manifest."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_MANIFEST = Path("agent-surfaces/manifest.json")
GENERATED_HEADER = "<!-- Generated by tools/render_agent_surfaces.py; edit agent-surfaces/* instead. -->"
VALID_STATUSES = {"ready", "partial", "unsupported"}
CODEX_FORBIDDEN = (
    "~/.claude",
    "CLAUDE_CODE_SESSION_ID",
    "ScheduleWakeup",
    "TeamCreate",
)
CODEX_SKILL_FORBIDDEN = (
    "TodoWrite",
    "AskUserQuestion",
    "Task tool",
    "subagent_type",
)
MAX_CODEX_HOOK_TIMEOUT_SECONDS = 900


def _load_manifest(path: Path) -> dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8"))


def _read_fragment(root: Path, rel: str) -> str:
    path = root / rel
    return path.read_text(encoding="utf-8").strip()


def _render_document(root: Path, manifest: dict[str, Any], host: str) -> str:
    docs = manifest["documents"]
    host_doc = docs["hosts"][host]
    parts = [GENERATED_HEADER, "", f"# {host_doc['title']}", ""]
    for rel in docs["shared_fragments"]:
        parts.append(_read_fragment(root, rel))
        parts.append("")
    for rel in host_doc["fragments"]:
        parts.append(_read_fragment(root, rel))
        parts.append("")
    return "\n".join(parts).rstrip() + "\n"


def _render_codex_hooks(manifest: dict[str, Any]) -> str:
    hooks: dict[str, list[dict[str, Any]]] = {}
    for hook in manifest.get("hooks", []):
        host = hook.get("hosts", {}).get("codex", {})
        if host.get("status") != "ready":
            continue
        for event in host.get("events", []):
            command = event["command"]
            item: dict[str, Any] = {
                "matcher": event.get("matcher", ""),
                "hooks": [{"type": "command", "command": command}],
            }
            timeout = event.get("timeout_seconds")
            if timeout is not None:
                item["hooks"][0]["timeout"] = timeout
            hooks.setdefault(event["event"], []).append(item)
    return json.dumps({"hooks": hooks}, indent=2, sort_keys=True) + "\n"


def rendered_targets(root: Path, manifest: dict[str, Any]) -> dict[Path, str]:
    docs = manifest["documents"]["hosts"]
    targets = {
        root / docs["codex"]["target"]: _render_document(root, manifest, "codex"),
        root / docs["claude"]["target"]: _render_document(root, manifest, "claude"),
        root / ".codex" / "hooks.json": _render_codex_hooks(manifest),
    }
    return targets


def _validate_host_entry(kind: str, item_id: str, host: str, entry: dict[str, Any], errors: list[str]) -> None:
    status = entry.get("status")
    if status not in VALID_STATUSES:
        errors.append(f"{kind} {item_id}: host {host} has invalid status {status!r}")
        return
    if status == "ready":
        if kind == "hook" and not entry.get("fixtures"):
            errors.append(f"hook {item_id}: host {host} ready without fixtures")
        if not entry.get("events") and kind == "hook":
            errors.append(f"hook {item_id}: host {host} ready without events")
    if status in {"partial", "unsupported"} and not entry.get("unsupported_reason"):
        errors.append(f"{kind} {item_id}: host {host} {status} without unsupported_reason")


def _validate_fixture(root: Path, kind: str, item_id: str, host: str, fixture: str, errors: list[str]) -> None:
    path_text, _, selector = fixture.partition("::")
    path = root / path_text
    if kind == "hook" and host == "codex":
        if not selector or path.suffix != ".py":
            errors.append(f"{kind} {item_id}: host {host} Codex hook fixture must be a pytest selector: {fixture}")
        elif "codex" not in selector.lower():
            errors.append(f"{kind} {item_id}: host {host} Codex hook fixture must be Codex-specific: {fixture}")
    if not path.exists():
        errors.append(f"{kind} {item_id}: host {host} fixture does not exist: {fixture}")
        return
    if selector:
        text = path.read_text(encoding="utf-8", errors="replace")
        selector_name = selector.split("[", 1)[0]
        if f"def {selector_name}(" not in text and f"class {selector_name}" not in text:
            errors.append(f"{kind} {item_id}: host {host} fixture selector not found: {fixture}")


def _frontmatter(text: str) -> dict[str, str] | None:
    lines = text.splitlines()
    if not lines or lines[0].strip() != "---":
        return None
    values: dict[str, str] = {}
    for line in lines[1:]:
        if line.strip() == "---":
            return values
        if ":" not in line or line.startswith(" "):
            continue
        key, value = line.split(":", 1)
        values[key.strip()] = value.strip().strip('"')
    return None


def _validate_codex_skill(root: Path, skill: dict[str, Any], errors: list[str]) -> None:
    item_id = skill.get("id", "<missing>")
    target = skill.get("target")
    if not target:
        errors.append(f"skill {item_id}: missing target")
        return
    path = root / target
    if not path.exists():
        errors.append(f"skill {item_id}: target missing: {target}")
        return

    text = path.read_text(encoding="utf-8", errors="replace")
    if len(text.strip()) < 200:
        errors.append(f"skill {item_id}: Codex skill is empty or too small")

    frontmatter = _frontmatter(text)
    if frontmatter is None:
        errors.append(f"skill {item_id}: Codex skill missing YAML frontmatter")
    else:
        if frontmatter.get("name") != item_id:
            errors.append(f"skill {item_id}: frontmatter name does not match id")
        if not frontmatter.get("description"):
            errors.append(f"skill {item_id}: frontmatter missing description")

    lowered = text.lower()
    if "openspec" not in lowered:
        errors.append(f"skill {item_id}: Codex skill lacks OpenSpec workflow content")
    for token in CODEX_SKILL_FORBIDDEN:
        if token in text:
            errors.append(f"skill {item_id}: Codex skill references unavailable tool token: {token}")
    for token in CODEX_FORBIDDEN:
        if token in text:
            errors.append(f"skill {item_id}: Codex skill contains forbidden Claude-only token: {token}")


def validate_manifest(root: Path, manifest: dict[str, Any]) -> list[str]:
    errors: list[str] = []
    for host in ("codex", "claude"):
        if host not in manifest.get("documents", {}).get("hosts", {}):
            errors.append(f"documents missing host {host}")

    for hook in manifest.get("hooks", []):
        item_id = hook.get("id", "<missing>")
        hosts = hook.get("hosts", {})
        for host in ("codex", "claude"):
            if host not in hosts:
                errors.append(f"hook {item_id}: missing host {host}")
                continue
            _validate_host_entry("hook", item_id, host, hosts[host], errors)
            for fixture in hosts[host].get("fixtures", []):
                _validate_fixture(root, "hook", item_id, host, fixture, errors)
        codex = hosts.get("codex", {})
        if codex.get("status") == "ready":
            source = hook.get("source")
            if source and source != "bd" and Path(source).suffix == ".py":
                fixture_text = "\n".join(codex.get("fixtures", [])).lower().replace("-", "_")
                source_stem = Path(source).stem.lower().replace("-", "_")
                hook_id = item_id.lower().replace("-", "_")
                if source_stem not in fixture_text and hook_id not in fixture_text:
                    errors.append(f"hook {item_id}: Codex hook fixture must match hook source: {source}")
            for event in codex.get("events", []):
                command = event.get("command", "")
                if "timeout" in event:
                    errors.append(f"hook {item_id}: Codex event must use timeout_seconds, not timeout")
                timeout = event.get("timeout_seconds")
                if timeout is not None:
                    if not isinstance(timeout, int) or timeout <= 0:
                        errors.append(f"hook {item_id}: Codex timeout_seconds must be a positive integer")
                    elif timeout > MAX_CODEX_HOOK_TIMEOUT_SECONDS:
                        errors.append(
                            f"hook {item_id}: Codex timeout_seconds exceeds "
                            f"{MAX_CODEX_HOOK_TIMEOUT_SECONDS}: {timeout}"
                        )
                if "~/.claude" in command:
                    errors.append(f"hook {item_id}: Codex command uses ~/.claude")
                if not command:
                    errors.append(f"hook {item_id}: Codex event missing command")
                source = hook.get("source")
                if source and source != "bd" and not (root / source).exists():
                    errors.append(f"hook {item_id}: source does not exist: {source}")

    manifest_skill_targets = {skill.get("target") for skill in manifest.get("skills", [])}
    actual_skill_targets = {
        path.relative_to(root).as_posix()
        for path in sorted((root / ".agents" / "skills").glob("*/SKILL.md"))
    }
    missing_from_manifest = actual_skill_targets - manifest_skill_targets
    extra_in_manifest = {target for target in manifest_skill_targets if target} - actual_skill_targets
    for target in sorted(missing_from_manifest):
        errors.append(f"skill target not listed in manifest: {target}")
    for target in sorted(extra_in_manifest):
        errors.append(f"manifest skill target missing from workspace: {target}")

    for skill in manifest.get("skills", []):
        item_id = skill.get("id", "<missing>")
        hosts = skill.get("hosts", {})
        for host in ("codex", "claude"):
            if host not in hosts:
                errors.append(f"skill {item_id}: missing host {host}")
                continue
            _validate_host_entry("skill", item_id, host, hosts[host], errors)
        if hosts.get("codex", {}).get("status") == "ready":
            _validate_codex_skill(root, skill, errors)

    return errors


def validate_codex_surfaces(targets: dict[Path, str], manifest: dict[str, Any]) -> list[str]:
    errors: list[str] = []
    codex_text = targets[next(path for path in targets if path.name == "AGENTS.md")]
    codex_hooks = targets[next(path for path in targets if path.as_posix().endswith(".codex/hooks.json"))]
    for needle in CODEX_FORBIDDEN:
        if needle in codex_text or needle in codex_hooks:
            errors.append(f"Codex surface contains forbidden Claude-only token: {needle}")

    hooks = json.loads(codex_hooks)["hooks"]
    commands = [
        hook["command"]
        for event_items in hooks.values()
        for item in event_items
        for hook in item["hooks"]
    ]
    if "bd prime" not in commands:
        errors.append("Codex hooks must include bd prime")
    if not any(command != "bd prime" for command in commands):
        errors.append("Codex hooks must include at least one behavioral gate beyond bd prime")
    return errors


def check(root: Path, manifest_path: Path) -> int:
    manifest = _load_manifest(manifest_path)
    targets = rendered_targets(root, manifest)
    errors = validate_manifest(root, manifest)
    errors.extend(validate_codex_surfaces(targets, manifest))

    for path, expected in targets.items():
        if not path.exists():
            errors.append(f"generated target missing: {path.relative_to(root)}")
            continue
        actual = path.read_text(encoding="utf-8")
        if actual != expected:
            errors.append(f"generated target drift: {path.relative_to(root)}")

    if errors:
        for error in errors:
            print(error, file=sys.stderr)
        return 1
    return 0


def render(root: Path, manifest_path: Path) -> int:
    manifest = _load_manifest(manifest_path)
    for path, content in rendered_targets(root, manifest).items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
    return 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail if generated files drift")
    parser.add_argument("--manifest", default=str(DEFAULT_MANIFEST))
    parser.add_argument("--root", default=".")
    args = parser.parse_args(argv)

    root = Path(args.root).resolve()
    manifest_path = Path(args.manifest)
    if not manifest_path.is_absolute():
        manifest_path = root / manifest_path
    if args.check:
        return check(root, manifest_path)
    return render(root, manifest_path)


if __name__ == "__main__":
    raise SystemExit(main())
