#!/usr/bin/env python3
"""Render and check host-specific agent surfaces from a neutral manifest."""
# file-complexity-waiver: multi-host surface renderer (Codex + Claude plugin trees + docs) is one cohesive responsibility — a manifest->targets map; extracting plugin-rendering into a sibling module is tracked as follow-up if it keeps growing.

from __future__ import annotations

import argparse
import json
import os
import shlex
import shutil
import sys
import tempfile
from pathlib import Path
from typing import Any

try:
    from agent_surface_identity import (
        validate_canonical_identity,
        validate_identity_surfaces,
        validate_support_manifest,
    )
except ModuleNotFoundError:  # Imported by a path-based test module from the repository root.
    from tools.agent_surface_identity import (
        validate_canonical_identity,
        validate_identity_surfaces,
        validate_support_manifest,
    )

try:
    from pi_agent_surface import (
        PI_HOOK_SUPPORT,
        PI_PLUGIN_ROOT,
        ready_bash_gates as _pi_ready_bash_gates,
        ready_file_gates as _pi_ready_file_gates,
        render_gate_inventory as _render_pi_gate_inventory,
        render_package as _render_pi_package,
        validate_adapter as _validate_pi_adapter,
    )
except ModuleNotFoundError:
    from tools.pi_agent_surface import (
        PI_HOOK_SUPPORT,
        PI_PLUGIN_ROOT,
        ready_bash_gates as _pi_ready_bash_gates,
        ready_file_gates as _pi_ready_file_gates,
        render_gate_inventory as _render_pi_gate_inventory,
        render_package as _render_pi_package,
        validate_adapter as _validate_pi_adapter,
    )


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_MANIFEST = Path("agent-surfaces/manifest.json")
DEFAULT_IDENTITY = Path("agent-surfaces/identity.json")
GENERATED_HEADER = "<!-- Generated by tools/render_agent_surfaces.py; edit agent-surfaces/* instead. -->"
CODEX_PLUGIN_ROOT = Path("plugins/escapement")
CLAUDE_PLUGIN_ROOT = Path("plugins/escapement-claude")
VALID_STATUSES = {"ready", "partial", "unsupported"}
MISSION_START = "<!-- escapement:mission:start -->"
MISSION_END = "<!-- escapement:mission:end -->"
CAPABILITIES_START = "<!-- escapement:capabilities:start -->"
CAPABILITIES_END = "<!-- escapement:capabilities:end -->"
ADAPTER_MAPPING_START = "<!-- escapement:adapter-mapping:start -->"
ADAPTER_MAPPING_END = "<!-- escapement:adapter-mapping:end -->"
SHARED_HOOK_SUPPORT = {
    "claude/hooks/_worktree_cli.py",
    "claude/hooks/_gate_signal.py",
    "claude/hooks/_advisory_dedupe.py",
    "claude/hooks/_local_judge_client.py",
    "claude/hooks/_gh_command.py",
    # Landing-time gates share repository-neutral origin/HEAD + merge-base
    # authority. Omitting this sibling makes installed hooks fail open.
    "claude/hooks/git_change_scope.py",
    # Reader for Codex's apply_patch payload, imported by every gate that has
    # to work on Codex. Same failure mode: without it the import fails, the
    # gate fails open, and it is inert exactly where it was needed.
    "claude/hooks/_codex_patch.py",
    # One owner for how a hook speaks to a host. A wrong wire shape is silent:
    # the hook fires, decides correctly, and nothing happens.
    "claude/hooks/_host_output.py",
    # Both advisory boundaries use the corpus-backed per-function strength
    # differ; its parser is a required transitive sibling in installed hosts.
    "claude/hooks/oracle_strength_diff.py",
    "claude/hooks/oracle_strength_parse.py",
    # implementation_echo_test_gate imports this policy helper in both hosts.
    # Omitting it makes the defensive import fallback hard-deny fixture echoes.
    "claude/hooks/data_fixture_echo.py",
    # implementation_echo_test_gate imports both analyzers in both hosts.
    # Omitting either silently activates a permissive defensive fallback.
    "claude/hooks/magic_number_echo.py",
    "claude/hooks/oracle_reason_validation.py",
    # test_oracle_brief_gate keeps path/content and landing-command policy in
    # bounded siblings shared byte-for-byte by both host packages.
    "claude/hooks/oracle_brief_rapid.py",
    "claude/hooks/test_oracle_brief_policy.py",
    "claude/hooks/test_oracle_brief_landing.py",
}
SHARED_RUNTIME_SUPPORT = {
    "bin/escapement-worktree",
    "bin/escapement_worktree.py",
    "bin/escapement_worktree_activity.py",
    "bin/escapement_worktree_allocate_ref.py",
    "bin/escapement_worktree_bootstrap.py",
    "bin/escapement_worktree_cleanup.py",
    "bin/escapement_worktree_finish.py",
    "bin/escapement_worktree_git.py",
    "bin/escapement_worktree_github.py",
    "bin/escapement_worktree_registry.py",
    "bin/escapement_worktree_recovery.py",
    "bin/escapement_worktree_rollback_fs.py",
    "bin/escapement_worktree_rollback_lock.py",
    "bin/escapement_worktree_rollback_ref.py",
    "bin/escapement_worktree_root.py",
}
CODEX_HOOK_SUPPORT = {
    # Codex Bash policy gates execute through one in-process dispatcher to avoid
    # multiplying interpreter startup and filesystem pressure per tool call.
    "claude/hooks/codex_pretool_dispatch.py",
    # Retain partial hook sources for isolated fixtures and byte-parity checks
    # without registering them against an unverified Codex payload boundary.
    "claude/hooks/root_checkout_guard.py",
    "claude/hooks/_local_judge_client.py",
    # merge_authorization_gate.py resolves this sibling via its plugin-relative
    # path. Without it, an explicitly authorized Codex repository is denied
    # fail-closed because the policy reader cannot be imported.
    "harness/bin/repo_outcome.py",
    # codex_stop_hook.py imports its decision core rather than reimplementing it;
    # verify_integrity.py is would_block_stop's own transitive sibling. Without
    # both, the Stop hook raises ImportError, fails open, and the Codex adapter
    # is inert in exactly the wind-down it was added to catch.
    "harness/bin/would_block_stop.py",
    "harness/bin/verify_integrity.py",
    "harness/bin/schedule_store.py",
    "harness/bin/session_observer.py",
    "harness/bin/continuation_watchdog.py",
    "harness/bin/task_session_mode.py",
    "harness/bin/thread_identity.py",
    "harness/bin/trusted_json.py",
    "harness/bin/trusted_source.py",
    "harness/bin/wakeup_dispatch.py",
    "harness/bin/wakeup_waker.py",
    "harness/bin/winddown_gate.py",
    "harness/bin/winddown_judge.py",
    "harness/bin/worktree_lifecycle_supervisor.py",
    "harness/schemas/contract.schema.json",
    "harness/schemas/executions.schema.json",
    "harness/schemas/scheduled.schema.json",
}
CLAUDE_EXTRA_HOOK_SUPPORT = {
    "claude/hooks/local_judge_health.py",
}

# SessionStart rules-injection script for the Claude plugin. Emits the bundled
# claude/rules/* as additionalContext with (1) imperative framing so injected
# rules carry the same authority as native CLAUDE.md, and (2) fail-loud on a
# missing bundle (vs a silent exit 0) so a broken install is observable.
#
# A rule may wrap reference material — worked examples, exemption catalogues,
# step-by-step how-tos — in DETAIL_START/DETAIL_END markers. Those regions stay
# on disk and are replaced at injection time by a pointer to the rule's own
# path, which the agent reads when it reaches the situation that needs them.
# Concatenating every rule in full spent the same context on a 70-line worked
# example as on the sentence that changes what an agent does next.
#
# Regions rather than a single split point, because these files alternate rule,
# how-to, rule, how-to. Truncating at the first how-to would have dropped
# load-bearing imperatives ("ship it live", outcome-bias) that happen to sit
# below it, and reordering the files to make the tail contiguous would risk the
# same loss less visibly.
#
# The split is authored per rule rather than derived from "does a hook enforce
# this", because a gate that fires without the rule explaining its repair is a
# blocking gate, not a teaching one. An unmarked rule is injected whole, so the
# default stays safe and marking is opt-in.
INJECT_RULES_SH = r'''#!/usr/bin/env bash
# GENERATED by tools/render_agent_surfaces.py — edit the renderer, not this file.
# Escapement always-on rules injection (SessionStart).
set -uo pipefail
RULES_DIR="${CLAUDE_PLUGIN_ROOT:-$(cd "$(dirname "$0")/.." && pwd)}/rules"
python3 - "$RULES_DIR" <<'PY'
import glob, json, os, re, sys

DETAIL_START = "<!-- escapement:detail:start -->"
DETAIL_END = "<!-- escapement:detail:end -->"

rules_dir = sys.argv[1]
files = sorted(glob.glob(os.path.join(rules_dir, "*.md")))
if not files:
    ctx = (
        "[escapement] WARNING: rules bundle not found at %s. Escapement discipline "
        "rules were NOT injected this session — the plugin install may be incomplete. "
        "Reinstall/update the escapement plugin." % rules_dir
    )
else:
    parts = [
        "IMPORTANT — Escapement workflow rules (always-on, injected at session "
        "start). These instructions OVERRIDE default behavior and you MUST follow "
        "them exactly. Where a rule ends with a pointer to its own file, the rest "
        "of that rule is reference detail — read %s/<file> when you reach the "
        "situation it covers:\n" % rules_dir
    ]
    for f in files:
        try:
            text = open(f, encoding="utf-8").read()
        except OSError as exc:
            parts.append("[escapement] WARNING: could not read %s (%s)" % (f, exc))
            continue
        stripped = 0
        while DETAIL_START in text and DETAIL_END in text:
            head, rest = text.split(DETAIL_START, 1)
            _, tail = rest.split(DETAIL_END, 1)
            text = head.rstrip() + "\n\n" + tail.lstrip()
            stripped += 1
        # HTML comments are markup for the renderer and its tests -- the
        # support-claims blocks, for instance -- not instructions. Injecting
        # them spends context presenting key=value metadata as though it were
        # a rule.
        text = re.sub(r"<!--.*?-->", "", text, flags=re.S)
        if stripped:
            text = text.rstrip() + (
                "\n\n(%d reference section(s) held back — read %s for them.)"
                % (stripped, os.path.basename(f))
            )
        parts.append(text)
    ctx = "\n\n".join(parts)
print(json.dumps({
    "hookSpecificOutput": {
        "hookEventName": "SessionStart",
        "additionalContext": ctx,
    }
}))
PY
'''
CODEX_FORBIDDEN = (
    "~/.claude",
    "CLAUDE_CODE_SESSION_ID",
    "ScheduleWakeup",
    "TeamCreate",
)
CODEX_SKILL_FORBIDDEN = (
    "TodoWrite",
    "AskUserQuestion",
    "Task tool",
    "subagent_type",
)
MAX_CODEX_HOOK_TIMEOUT_SECONDS = 900
CODEX_DISPATCH_OVERHEAD_SECONDS_PER_GATE = 1


def _load_manifest(path: Path) -> dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8"))


def _load_identity(path: Path) -> dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8"))


def _read_fragment(root: Path, rel: str) -> str:
    path = root / rel
    return path.read_text(encoding="utf-8").strip()


def _render_fragment(root: Path, rel: str, identity: dict[str, Any]) -> str:
    text = _read_fragment(root, rel)
    if rel != "agent-surfaces/onboarding/shared.md":
        return text
    if MISSION_START in text and MISSION_END in text:
        before, remainder = text.split(MISSION_START, 1)
        _current, after = remainder.split(MISSION_END, 1)
        mission = identity.get("mission", "")
        text = f"{before}{MISSION_START}\n{mission}\n{MISSION_END}{after}"
    if CAPABILITIES_START in text and CAPABILITIES_END in text:
        before, remainder = text.split(CAPABILITIES_START, 1)
        _current, after = remainder.split(CAPABILITIES_END, 1)
        capabilities = "\n".join(
            f"{index}. {capability}"
            for index, capability in enumerate(identity.get("capabilities", ()), start=1)
        )
        text = f"{before}{CAPABILITIES_START}\n{capabilities}\n{CAPABILITIES_END}{after}"
    if ADAPTER_MAPPING_START in text and ADAPTER_MAPPING_END in text:
        before, remainder = text.split(ADAPTER_MAPPING_START, 1)
        _current, after = remainder.split(ADAPTER_MAPPING_END, 1)
        mapping = "\n".join(
            f"- {capability} | {', '.join(tools)}"
            for capability, tools in identity.get("current_adapters", {}).items()
        )
        text = f"{before}{ADAPTER_MAPPING_START}\n{mapping}\n{ADAPTER_MAPPING_END}{after}"
    return text


def _render_document(
    root: Path,
    manifest: dict[str, Any],
    identity: dict[str, Any],
    host: str,
) -> str:
    docs = manifest["documents"]
    host_doc = docs["hosts"][host]
    parts = [GENERATED_HEADER, "", f"# {host_doc['title']}", ""]
    for rel in docs["shared_fragments"]:
        parts.append(_render_fragment(root, rel, identity))
        parts.append("")
    for rel in host_doc["fragments"]:
        parts.append(_read_fragment(root, rel))
        parts.append("")
    return "\n".join(parts).rstrip() + "\n"


def _render_codex_hooks(manifest: dict[str, Any]) -> str:
    # The installable plugin is the sole Codex hook owner. Keep this generated
    # compatibility surface empty so opening the Escapement repository while the
    # plugin is installed cannot execute every lifecycle hook twice.
    return json.dumps({"hooks": {}}, indent=2, sort_keys=True) + "\n"


def _codex_plugin_command(command: str) -> str:
    for interpreter in ("python3 -B ", "python3 "):
        if not command.startswith(interpreter):
            continue
        tail = command[len(interpreter):]
        if not tail.startswith(("claude/hooks/", "harness/bin/")):
            return command
        script, separator, rest = tail.partition(" ")
        rewritten = f'{interpreter}"${{PLUGIN_ROOT}}/{script}"'
        if separator:
            rewritten += " " + rest
        return rewritten
    return command


def _render_codex_plugin_hooks(manifest: dict[str, Any]) -> str:
    hooks: dict[str, list[dict[str, Any]]] = {}
    bash_sources: list[str] = []
    bash_timeouts: list[int] = []
    for hook in manifest.get("hooks", []):
        host = hook.get("hosts", {}).get("codex", {})
        if host.get("status") != "ready":
            continue
        for event in host.get("events", []):
            if event.get("event") == "PreToolUse" and event.get("matcher") == "Bash":
                bash_sources.append(hook["source"])
                if event.get("timeout_seconds") is not None:
                    bash_timeouts.append(event["timeout_seconds"])

    dispatcher_rendered = False
    for hook in manifest.get("hooks", []):
        host = hook.get("hosts", {}).get("codex", {})
        if host.get("status") != "ready":
            continue
        for event in host.get("events", []):
            if event.get("event") == "PreToolUse" and event.get("matcher") == "Bash":
                if dispatcher_rendered:
                    continue
                command = (
                    'python3 -B "${PLUGIN_ROOT}/claude/hooks/'
                    'codex_pretool_dispatch.py"'
                )
                command += "".join(
                    f" --gate {shlex.quote(source)} --gate-timeout {timeout}"
                    for source, timeout in zip(
                        bash_sources, bash_timeouts, strict=True
                    )
                )
                item = {
                    "matcher": "Bash",
                    "hooks": [{"type": "command", "command": command}],
                }
                if bash_timeouts:
                    item["hooks"][0]["timeout"] = sum(bash_timeouts) + (
                        len(bash_timeouts) * CODEX_DISPATCH_OVERHEAD_SECONDS_PER_GATE
                    )
                hooks.setdefault("PreToolUse", []).append(item)
                dispatcher_rendered = True
                continue
            item: dict[str, Any] = {
                "matcher": event.get("matcher", ""),
                "hooks": [
                    {
                        "type": "command",
                        "command": _codex_plugin_command(event["command"]),
                    }
                ],
            }
            timeout = event.get("timeout_seconds")
            if timeout is not None:
                item["hooks"][0]["timeout"] = timeout
            hooks.setdefault(event["event"], []).append(item)
    return json.dumps({"hooks": hooks}, indent=2, sort_keys=True) + "\n"


def _render_codex_plugin_manifest(identity: dict[str, Any]) -> str:
    mission = identity["mission"]
    payload = {
        "name": "escapement",
        "version": "1.0.0",
        "description": mission,
        "author": {
            "name": "alexander-vyh",
            "url": "https://github.com/alexander-vyh",
        },
        "homepage": "https://github.com/alexander-vyh/escapement",
        "repository": "https://github.com/alexander-vyh/escapement",
        "license": "GPL-3.0-or-later",
        "keywords": [
            "workflow",
            "oracle",
            "tdd",
            "beads",
            "gates",
            "agentic",
        ],
        "skills": "./skills/",
        # Declare hooks explicitly rather than rely on Codex's undocumented default
        # discovery of hooks/hooks.json (escapement-z506). Verified accepted by
        # codex-cli 0.144.1: a plugin declaring `"hooks": "./hooks/hooks.json"`
        # installs cleanly. The embedded plugin-json-spec confirms the key
        # supplements (does not replace) default discovery.
        "hooks": "./hooks/hooks.json",
        "interface": {
            "displayName": "Escapement",
            "shortDescription": identity["short_description"],
            "longDescription": (
                f"{mission} Oracle-discipline gates block implementation-echo "
                "tests and oracle downgrades. TDD enforcement requires a Test "
                "Oracle Brief before writing code. Beads provides durable issue "
                "tracking. Works alongside your existing workflow."
            ),
            "developerName": "alexander-vyh",
            "category": "Developer Tools",
            "capabilities": [
                "Workflow gates",
                "TDD enforcement",
                "Issue tracking",
                "Oracle discipline",
            ],
            "websiteURL": "https://github.com/alexander-vyh/escapement",
            "defaultPrompt": [
                "Show me what work is ready in this repo.",
                "Check if I have a Test Oracle Brief before writing code.",
                "What Escapement gates are active in this session?",
            ],
            "brandColor": "#2D6A4F",
        },
    }
    return json.dumps(payload, indent=2) + "\n"


def _render_codex_marketplace() -> str:
    payload = {
        # Public-install name (escapement-z506). Verified: adding this repo via a
        # git URL (`codex plugin marketplace add https://github.com/alexander-vyh/
        # escapement`) resolves the plugin from its `local` source relative to the
        # cloned marketplace root, and `codex plugin marketplace upgrade escapement`
        # then tracks main — so the install command is `codex plugin add
        # escapement@escapement`, not the dev-only `@escapement-local`.
        "name": "escapement",
        "interface": {
            "displayName": "Escapement",
        },
        "plugins": [
            {
                "name": "escapement",
                "source": {
                    "source": "local",
                    "path": "./plugins/escapement",
                },
                "policy": {
                    "installation": "AVAILABLE",
                    "authentication": "ON_INSTALL",
                },
                "category": "Developer Tools",
            }
        ],
    }
    return json.dumps(payload, indent=2) + "\n"


def _codex_ready_hook_sources(manifest: dict[str, Any]) -> set[str]:
    return {
        hook["source"]
        for hook in manifest.get("hooks", [])
        if hook.get("source") != "bd" and hook.get("hosts", {}).get("codex", {}).get("status") == "ready"
    }


# Deployed-path -> vendored-plugin-path rewrites. Order matters: the more
# specific harness/bin prefix is checked before the generic hooks prefix.
# Args after the script (e.g. `--quiet`) are preserved.
_PLUGIN_PATH_REWRITES = (
    ("~/.claude/harness/bin/", "${CLAUDE_PLUGIN_ROOT}/harness/bin/"),
    ("~/.claude/hooks/", "${CLAUDE_PLUGIN_ROOT}/hooks/"),
)


def _claude_plugin_command(command: str) -> str:
    # Rewrite a deployed ~/.claude/{hooks,harness/bin}/<script> command to its
    # vendored plugin path. Commands outside those managed paths pass through.
    for prefix, repl in _PLUGIN_PATH_REWRITES:
        if prefix in command:
            head, tail = command.split(prefix, 1)
            script, sep, rest = tail.partition(" ")
            rebuilt = f'{head}"{repl}{script}"'
            if sep:
                rebuilt += " " + rest
            return rebuilt
    return command


def _render_claude_plugin_hooks(manifest: dict[str, Any]) -> str:
    hooks: dict[str, list[dict[str, Any]]] = {}
    for hook in manifest.get("hooks", []):
        host = hook.get("hosts", {}).get("claude", {})
        if host.get("status") != "ready":
            continue
        for event in host.get("events", []):
            command = event.get("command")
            if not command:
                continue
            item: dict[str, Any] = {
                "matcher": event.get("matcher", ""),
                "hooks": [
                    {"type": "command", "command": _claude_plugin_command(command)}
                ],
            }
            timeout = event.get("timeout_seconds")
            if timeout is not None:
                item["hooks"][0]["timeout"] = timeout
            hooks.setdefault(event["event"], []).append(item)
    # Always-on rules injection (the rules extension point for plugins).
    hooks.setdefault("SessionStart", []).append({
        "matcher": "startup|clear|compact",
        "hooks": [
            {
                "type": "command",
                "command": 'bash "${CLAUDE_PLUGIN_ROOT}/hooks/inject-rules.sh"',
            }
        ],
    })
    return json.dumps({"hooks": hooks}, indent=2, sort_keys=True) + "\n"


def _render_claude_plugin_manifest(identity: dict[str, Any]) -> str:
    payload = {
        "$schema": "https://anthropic.com/claude-code/plugin.schema.json",
        "name": "escapement",
        "description": identity["mission"],
        # NO `version` field — deliberate (escapement-9mki). Claude Code resolves an
        # unversioned plugin's version from the git commit SHA of the git-subdir
        # source, so every commit to main is a new version and `claude plugin update`
        # actually advances the install. A static `version` (e.g. "1.0.0") pins
        # resolution to that literal and makes `claude plugin update` a permanent
        # no-op. Verified 2026-07-10 against a real git-subdir-from-GitHub probe:
        # unversioned install updated 99d69bd->bf09f86 on a new commit; a static
        # version reported "already at latest". Do NOT add a version field back.
        "author": {"name": "alexander-vyh"},
        "repository": "https://github.com/alexander-vyh/escapement",
        "homepage": "https://github.com/alexander-vyh/escapement",
        "license": "GPL-3.0-or-later",
        "keywords": [
            "workflow",
            "beads",
            "openspec",
            "tdd",
            "continuation-harness",
        ],
    }
    return json.dumps(payload, indent=2) + "\n"


def _render_claude_marketplace(identity: dict[str, Any]) -> str:
    payload = {
        "$schema": "https://anthropic.com/claude-code/marketplace.schema.json",
        "name": "escapement",
        "description": identity["mission"],
        "owner": {"name": "alexander-vyh"},
        "plugins": [
            {
                "name": "escapement",
                "description": (
                    f"{identity['mission']} Always-on rules are injected via a "
                    "SessionStart hook. Unversioned, so `claude "
                    "plugin update escapement@escapement` tracks main automatically; "
                    "scripts/plugin-update.sh forces a refresh and also preserves "
                    "your model key and prunes duplicate hook registrations."
                ),
                "source": {
                    "source": "git-subdir",
                    "url": "https://github.com/alexander-vyh/escapement",
                    "path": "plugins/escapement-claude",
                    "ref": "main",
                },
                "category": "development",
                "author": {"name": "alexander-vyh"},
                "homepage": "https://github.com/alexander-vyh/escapement",
            }
        ],
    }
    return json.dumps(payload, indent=2) + "\n"


def _claude_ready_hook_sources(manifest: dict[str, Any]) -> set[str]:
    return {
        hook["source"]
        for hook in manifest.get("hooks", [])
        if hook.get("source") != "bd"
        and hook.get("hosts", {}).get("claude", {}).get("status") == "ready"
    }


def rendered_targets(
    root: Path,
    manifest: dict[str, Any],
    identity: dict[str, Any] | None = None,
) -> dict[Path, str]:
    if identity is None:
        identity = _load_identity(root / DEFAULT_IDENTITY)
    docs = manifest["documents"]["hosts"]
    targets = {
        root / docs["codex"]["target"]: _render_document(root, manifest, identity, "codex"),
        root / docs["claude"]["target"]: _render_document(root, manifest, identity, "claude"),
        root / docs["pi"]["target"]: _render_document(root, manifest, identity, "pi"),
        root / "package.json": _render_pi_package(identity),
        root / PI_PLUGIN_ROOT / "gates.json": _render_pi_gate_inventory(manifest),
        root / PI_PLUGIN_ROOT / "extensions" / "index.ts": (
            root / "agent-surfaces" / "hosts" / "pi" / "extensions" / "index.ts"
        ).read_text(encoding="utf-8"),
        root / ".codex" / "hooks.json": _render_codex_hooks(manifest),
        root / ".agents" / "plugins" / "marketplace.json": _render_codex_marketplace(),
        root / CODEX_PLUGIN_ROOT / ".codex-plugin" / "plugin.json": _render_codex_plugin_manifest(identity),
        root / CODEX_PLUGIN_ROOT / "hooks" / "hooks.json": _render_codex_plugin_hooks(manifest),
    }

    for skill_path in sorted((root / ".agents" / "skills").glob("*/SKILL.md")):
        rel = skill_path.relative_to(root / ".agents")
        targets[root / CODEX_PLUGIN_ROOT / rel] = skill_path.read_text(encoding="utf-8")

    for source in sorted(SHARED_RUNTIME_SUPPORT):
        content = (root / source).read_text(encoding="utf-8")
        targets[root / CODEX_PLUGIN_ROOT / source] = content
        targets[root / CLAUDE_PLUGIN_ROOT / source] = content
        targets[root / PI_PLUGIN_ROOT / source] = content

    hook_sources = _codex_ready_hook_sources(manifest)
    if hook_sources:
        hook_sources.update(SHARED_HOOK_SUPPORT)
    for source in sorted(hook_sources):
        source_path = root / source
        if source_path.exists():
            targets[root / CODEX_PLUGIN_ROOT / source] = source_path.read_text(encoding="utf-8")
    for source in sorted(CODEX_HOOK_SUPPORT):
        source_path = root / source
        if source_path.exists():
            targets[root / CODEX_PLUGIN_ROOT / source] = source_path.read_text(encoding="utf-8")

    # Both gate lists. gates.json names a gate by path and the dispatcher opens
    # it from the plugin root, so a gate listed but not vendored is a gate that
    # cannot run -- the inventory looks right and the brake is not there.
    pi_hook_sources = {
        gate["source"]
        for gate in [*_pi_ready_bash_gates(manifest), *_pi_ready_file_gates(manifest)]
    }
    pi_hook_sources.update(SHARED_HOOK_SUPPORT | PI_HOOK_SUPPORT)
    for source in sorted(pi_hook_sources):
        source_path = root / source
        if source_path.exists():
            targets[root / PI_PLUGIN_ROOT / source] = source_path.read_text(encoding="utf-8")

    # --- Claude plugin tree (plugins/escapement-claude) + root marketplace ---
    targets[root / ".claude-plugin" / "marketplace.json"] = _render_claude_marketplace(identity)
    targets[root / CLAUDE_PLUGIN_ROOT / ".claude-plugin" / "plugin.json"] = _render_claude_plugin_manifest(identity)
    targets[root / CLAUDE_PLUGIN_ROOT / "hooks" / "hooks.json"] = _render_claude_plugin_hooks(manifest)
    targets[root / CLAUDE_PLUGIN_ROOT / "hooks" / "inject-rules.sh"] = INJECT_RULES_SH

    # Bundle the always-on rules (injected at SessionStart by inject-rules.sh).
    for rule_path in sorted((root / "claude" / "rules").glob("*.md")):
        targets[root / CLAUDE_PLUGIN_ROOT / "rules" / rule_path.name] = rule_path.read_text(encoding="utf-8")

    # Vendor Claude skills, commands, and agents at the plugin's default locations.
    for skill_path in sorted((root / "claude" / "skills").glob("*/SKILL.md")):
        rel = skill_path.relative_to(root / "claude")
        targets[root / CLAUDE_PLUGIN_ROOT / rel] = skill_path.read_text(encoding="utf-8")
    for cmd_path in sorted((root / "claude" / "commands").glob("*.md")):
        targets[root / CLAUDE_PLUGIN_ROOT / "commands" / cmd_path.name] = cmd_path.read_text(encoding="utf-8")
    for agent_path in sorted((root / "claude" / "agents").glob("*.md")):
        targets[root / CLAUDE_PLUGIN_ROOT / "agents" / agent_path.name] = agent_path.read_text(encoding="utf-8")

    # Vendor Claude-ready hook sources into hooks/ (flat) plus the shared
    # _gate_signal helper, so a hook's `from _gate_signal import record` resolves.
    claude_hook_sources = _claude_ready_hook_sources(manifest)
    if claude_hook_sources:
        claude_hook_sources.update(SHARED_HOOK_SUPPORT | CLAUDE_EXTRA_HOOK_SUPPORT)
    for source in sorted(claude_hook_sources):
        # harness/* sources are vendored wholesale into harness/ below, not flat into hooks/.
        if source.startswith("harness/"):
            continue
        source_path = root / source
        if source_path.exists():
            targets[root / CLAUDE_PLUGIN_ROOT / "hooks" / Path(source).name] = source_path.read_text(encoding="utf-8")

    # Bundle the continuation-harness (bin + schemas) so its hooks run from the
    # plugin via ${CLAUDE_PLUGIN_ROOT}/harness/bin. Runtime STATE still resolves to
    # ~/.claude/harness (DEFAULT_HARNESS_ROOT), independent of this read-only code.
    for sub in ("bin", "schemas"):
        src_dir = root / "harness" / sub
        for hpath in sorted(src_dir.glob("*")):
            if hpath.is_file():
                targets[root / CLAUDE_PLUGIN_ROOT / "harness" / sub / hpath.name] = \
                    hpath.read_text(encoding="utf-8")

    return targets


def _is_within(path: Path, parent: Path) -> bool:
    try:
        path.relative_to(parent)
    except ValueError:
        return False
    return True


def _publication_units(root: Path, targets: dict[Path, str]) -> tuple[Path, ...]:
    """Return atomic replacement units for generated files and complete plugin trees."""

    managed_roots = (CODEX_PLUGIN_ROOT, CLAUDE_PLUGIN_ROOT, PI_PLUGIN_ROOT)
    units = {Path(".codex-plugin"), *managed_roots}
    for target in targets:
        relative = target.relative_to(root)
        if not any(_is_within(relative, managed_root) for managed_root in managed_roots):
            units.add(relative)
    return tuple(sorted(units, key=lambda path: (len(path.parts), path.as_posix())))


def _stage_targets(root: Path, targets: dict[Path, str], prepared: Path) -> None:
    """Write the complete next generation without modifying any published surface."""

    for path, content in targets.items():
        staged = prepared / path.relative_to(root)
        staged.parent.mkdir(parents=True, exist_ok=True)
        staged.write_text(content, encoding="utf-8")
        if staged.name == "escapement-worktree" and staged.parent.name == "bin":
            staged.chmod(0o755)


def _remove_published_path(path: Path) -> None:
    if path.is_dir() and not path.is_symlink():
        shutil.rmtree(path)
    elif path.exists() or path.is_symlink():
        path.unlink()


def _publish_staged(root: Path, prepared: Path, backup: Path, units: tuple[Path, ...]) -> None:
    """Publish all staged units transactionally, restoring old state on any failure."""

    states: list[tuple[Path, Path, bool]] = []
    try:
        for relative in units:
            destination = root / relative
            staged = prepared / relative
            saved = backup / relative
            had_existing = destination.exists() or destination.is_symlink()
            if had_existing:
                saved.parent.mkdir(parents=True, exist_ok=True)
                os.replace(destination, saved)
            states.append((destination, saved, had_existing))
            if staged.exists() or staged.is_symlink():
                destination.parent.mkdir(parents=True, exist_ok=True)
                os.replace(staged, destination)
    except OSError as publish_error:
        rollback_errors: list[str] = []
        for destination, saved, had_existing in reversed(states):
            try:
                _remove_published_path(destination)
                if had_existing:
                    destination.parent.mkdir(parents=True, exist_ok=True)
                    os.replace(saved, destination)
            except OSError as rollback_error:
                rollback_errors.append(f"{destination}: {rollback_error}")
        if rollback_errors:
            detail = "; ".join(rollback_errors)
            raise OSError(f"publish failed ({publish_error}); rollback incomplete: {detail}") from publish_error
        raise


def _validate_host_entry(kind: str, item_id: str, host: str, entry: dict[str, Any], errors: list[str]) -> None:
    status = entry.get("status")
    if status not in VALID_STATUSES:
        errors.append(f"{kind} {item_id}: host {host} has invalid status {status!r}")
        return
    if status == "ready":
        if kind == "hook" and not entry.get("fixtures"):
            errors.append(f"hook {item_id}: host {host} ready without fixtures")
        if not entry.get("events") and kind == "hook":
            errors.append(f"hook {item_id}: host {host} ready without events")
    if status in {"partial", "unsupported"} and not entry.get("unsupported_reason"):
        errors.append(f"{kind} {item_id}: host {host} {status} without unsupported_reason")


def _validate_fixture(root: Path, kind: str, item_id: str, host: str, fixture: str, errors: list[str]) -> None:
    path_text, _, selector = fixture.partition("::")
    path = root / path_text
    if kind == "hook" and host == "codex":
        if not selector or path.suffix != ".py":
            errors.append(f"{kind} {item_id}: host {host} Codex hook fixture must be a pytest selector: {fixture}")
        elif "codex" not in selector.lower():
            errors.append(f"{kind} {item_id}: host {host} Codex hook fixture must be Codex-specific: {fixture}")
    if not path.exists():
        errors.append(f"{kind} {item_id}: host {host} fixture does not exist: {fixture}")
        return
    if selector:
        text = path.read_text(encoding="utf-8", errors="replace")
        selector_name = selector.split("[", 1)[0]
        if f"def {selector_name}(" not in text and f"class {selector_name}" not in text:
            errors.append(f"{kind} {item_id}: host {host} fixture selector not found: {fixture}")


def _fixture_matches_hook_source(root: Path, fixture: str, source: str, item_id: str) -> bool:
    path_text, _, _selector = fixture.partition("::")
    fixture_path = root / path_text
    if not fixture_path.is_file():
        return False
    fixture_text = fixture_path.read_text(encoding="utf-8", errors="replace")
    normalized_fixture = fixture_text.lower().replace("-", "_")
    source_stem = Path(source).stem.lower().replace("-", "_")
    hook_id = item_id.lower().replace("-", "_")
    return source_stem in normalized_fixture or hook_id in normalized_fixture


def _frontmatter(text: str) -> dict[str, str] | None:
    lines = text.splitlines()
    if not lines or lines[0].strip() != "---":
        return None
    values: dict[str, str] = {}
    for line in lines[1:]:
        if line.strip() == "---":
            return values
        if ":" not in line or line.startswith(" "):
            continue
        key, value = line.split(":", 1)
        values[key.strip()] = value.strip().strip('"')
    return None


def _validate_codex_skill(root: Path, skill: dict[str, Any], errors: list[str]) -> None:
    item_id = skill.get("id", "<missing>")
    target = skill.get("target")
    if not target:
        errors.append(f"skill {item_id}: missing target")
        return
    path = root / target
    if not path.exists():
        errors.append(f"skill {item_id}: target missing: {target}")
        return

    text = path.read_text(encoding="utf-8", errors="replace")
    if len(text.strip()) < 200:
        errors.append(f"skill {item_id}: Codex skill is empty or too small")

    frontmatter = _frontmatter(text)
    if frontmatter is None:
        errors.append(f"skill {item_id}: Codex skill missing YAML frontmatter")
    else:
        if frontmatter.get("name") != item_id:
            errors.append(f"skill {item_id}: frontmatter name does not match id")
        if not frontmatter.get("description"):
            errors.append(f"skill {item_id}: frontmatter missing description")

    lowered = text.lower()
    if item_id.startswith("openspec-") and "openspec" not in lowered:
        errors.append(f"skill {item_id}: Codex skill lacks OpenSpec workflow content")
    for token in CODEX_SKILL_FORBIDDEN:
        if token in text:
            errors.append(f"skill {item_id}: Codex skill references unavailable tool token: {token}")
    for token in CODEX_FORBIDDEN:
        if token in text:
            errors.append(f"skill {item_id}: Codex skill contains forbidden Claude-only token: {token}")


def validate_manifest(root: Path, manifest: dict[str, Any]) -> list[str]:
    errors: list[str] = []
    for host in ("codex", "claude", "pi"):
        if host not in manifest.get("documents", {}).get("hosts", {}):
            errors.append(f"documents missing host {host}")

    errors.extend(_validate_pi_adapter(manifest))

    for hook in manifest.get("hooks", []):
        item_id = hook.get("id", "<missing>")
        hosts = hook.get("hosts", {})
        for host in ("codex", "claude"):
            if host not in hosts:
                errors.append(f"hook {item_id}: missing host {host}")
                continue
            _validate_host_entry("hook", item_id, host, hosts[host], errors)
            for fixture in hosts[host].get("fixtures", []):
                _validate_fixture(root, "hook", item_id, host, fixture, errors)
        codex = hosts.get("codex", {})
        if codex.get("status") == "ready":
            source = hook.get("source")
            if source and source != "bd" and Path(source).suffix == ".py":
                fixtures = codex.get("fixtures", [])
                if not any(
                    _fixture_matches_hook_source(root, fixture, source, item_id)
                    for fixture in fixtures
                ):
                    errors.append(f"hook {item_id}: Codex hook fixture must match hook source: {source}")
            for event in codex.get("events", []):
                command = event.get("command", "")
                if "timeout" in event:
                    errors.append(f"hook {item_id}: Codex event must use timeout_seconds, not timeout")
                timeout = event.get("timeout_seconds")
                if timeout is not None:
                    if not isinstance(timeout, int) or timeout <= 0:
                        errors.append(f"hook {item_id}: Codex timeout_seconds must be a positive integer")
                    elif timeout > MAX_CODEX_HOOK_TIMEOUT_SECONDS:
                        errors.append(
                            f"hook {item_id}: Codex timeout_seconds exceeds "
                            f"{MAX_CODEX_HOOK_TIMEOUT_SECONDS}: {timeout}"
                        )
                if "~/.claude" in command:
                    errors.append(f"hook {item_id}: Codex command uses ~/.claude")
                if not command:
                    errors.append(f"hook {item_id}: Codex event missing command")
                source = hook.get("source")
                if source and source != "bd" and not (root / source).exists():
                    errors.append(f"hook {item_id}: source does not exist: {source}")

    manifest_skill_targets = {skill.get("target") for skill in manifest.get("skills", [])}
    actual_skill_targets = {
        path.relative_to(root).as_posix()
        for path in sorted((root / ".agents" / "skills").glob("*/SKILL.md"))
    }
    missing_from_manifest = actual_skill_targets - manifest_skill_targets
    extra_in_manifest = {target for target in manifest_skill_targets if target} - actual_skill_targets
    for target in sorted(missing_from_manifest):
        errors.append(f"skill target not listed in manifest: {target}")
    for target in sorted(extra_in_manifest):
        errors.append(f"manifest skill target missing from workspace: {target}")

    for skill in manifest.get("skills", []):
        item_id = skill.get("id", "<missing>")
        hosts = skill.get("hosts", {})
        for host in ("codex", "claude"):
            if host not in hosts:
                errors.append(f"skill {item_id}: missing host {host}")
                continue
            _validate_host_entry("skill", item_id, host, hosts[host], errors)
        if hosts.get("codex", {}).get("status") == "ready":
            _validate_codex_skill(root, skill, errors)

    return errors


def validate_codex_surfaces(targets: dict[Path, str], manifest: dict[str, Any]) -> list[str]:
    errors: list[str] = []
    codex_text = targets[next(path for path in targets if path.name == "AGENTS.md")]
    codex_hooks = targets[next(path for path in targets if path.as_posix().endswith(".codex/hooks.json"))]
    plugin_hooks = targets[next(path for path in targets if path.as_posix().endswith("plugins/escapement/hooks/hooks.json"))]
    for needle in CODEX_FORBIDDEN:
        if needle in codex_text or needle in codex_hooks or needle in plugin_hooks:
            errors.append(f"Codex surface contains forbidden Claude-only token: {needle}")
    if "${CLAUDE_PLUGIN_ROOT}" in plugin_hooks:
        errors.append("Codex plugin hooks must not use CLAUDE_PLUGIN_ROOT")

    repo_hooks = json.loads(codex_hooks)["hooks"]
    if repo_hooks:
        errors.append(
            "repo-local Codex hooks must be empty because the plugin is the sole hook owner"
        )

    plugin_commands = [
        hook["command"]
        for event_items in json.loads(plugin_hooks)["hooks"].values()
        for item in event_items
        for hook in item["hooks"]
    ]
    if any("bd prime" in command for command in plugin_commands):
        errors.append("Codex hooks must not delegate workflow policy to bd prime")
    if not any("escapement_session_context.py" in command for command in plugin_commands):
        errors.append("Codex plugin hooks must include Escapement-owned session context")
    if not any("gate.py" in command for command in plugin_commands):
        errors.append(
            "Codex plugin hooks must include at least one behavioral gate beyond session context"
        )

    for required in (
        "test_oracle_brief_gate.py",
        "implementation_echo_test_gate.py",
        "oracle_downgrade_warning_gate.py",
    ):
        if not any(required in command for command in plugin_commands):
            errors.append(f"Codex plugin hooks must include {required}")
    return errors


def check(root: Path, manifest_path: Path) -> int:
    manifest = _load_manifest(manifest_path)
    identity = _load_identity(root / DEFAULT_IDENTITY)
    targets = rendered_targets(root, manifest, identity)
    errors = validate_manifest(root, manifest)
    errors.extend(validate_identity_surfaces(root, manifest, identity))
    errors.extend(validate_codex_surfaces(targets, manifest))

    for path, expected in targets.items():
        if not path.exists():
            errors.append(f"generated target missing: {path.relative_to(root)}")
            continue
        actual = path.read_text(encoding="utf-8")
        if actual != expected:
            errors.append(f"generated target drift: {path.relative_to(root)}")

    if errors:
        for error in errors:
            print(error, file=sys.stderr)
        return 1
    return 0


def render(root: Path, manifest_path: Path) -> int:
    manifest = _load_manifest(manifest_path)
    identity = _load_identity(root / DEFAULT_IDENTITY)
    errors = validate_manifest(root, manifest)
    errors.extend(validate_canonical_identity(identity))
    errors.extend(validate_support_manifest(manifest))
    if errors:
        for error in errors:
            print(error, file=sys.stderr)
        return 1

    targets = rendered_targets(root, manifest, identity)
    overrides = {path.relative_to(root): content for path, content in targets.items()}
    errors = validate_identity_surfaces(root, manifest, identity, overrides)
    errors.extend(validate_codex_surfaces(targets, manifest))
    if errors:
        for error in errors:
            print(error, file=sys.stderr)
        return 1

    try:
        with tempfile.TemporaryDirectory(prefix=".agent-surface-stage-", dir=root) as temporary:
            transaction = Path(temporary)
            prepared = transaction / "prepared"
            backup = transaction / "backup"
            _stage_targets(root, targets, prepared)
            _publish_staged(root, prepared, backup, _publication_units(root, targets))
    except OSError as error:
        print(f"agent surface publication failed: {error}", file=sys.stderr)
        return 1
    return 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail if generated files drift")
    parser.add_argument("--manifest", default=str(DEFAULT_MANIFEST))
    parser.add_argument("--root", default=".")
    args = parser.parse_args(argv)

    root = Path(args.root).resolve()
    manifest_path = Path(args.manifest)
    if not manifest_path.is_absolute():
        manifest_path = root / manifest_path
    if args.check:
        return check(root, manifest_path)
    return render(root, manifest_path)


if __name__ == "__main__":
    raise SystemExit(main())
