#!/usr/bin/env python3
"""Render and check host-specific agent surfaces from a neutral manifest."""
# file-complexity-waiver: multi-host surface renderer (Codex + Claude plugin trees + docs) is one cohesive responsibility — a manifest->targets map; extracting plugin-rendering into a sibling module is tracked as follow-up if it keeps growing.

from __future__ import annotations

import argparse
import json
import os
import shlex
import shutil
import sys
import tempfile
from pathlib import Path
from typing import Any

try:
    from agent_surface_identity import (
        validate_canonical_identity,
        validate_identity_surfaces,
        validate_support_manifest,
    )
except ModuleNotFoundError:  # Imported by a path-based test module from the repository root.
    from tools.agent_surface_identity import (
        validate_canonical_identity,
        validate_identity_surfaces,
        validate_support_manifest,
    )

try:
    from pi_agent_surface import (
        PI_MCP_CONFIG,
        PI_PLUGIN_ROOT,
        PI_SKILL_DIRS,
        pi_gate_sources as _pi_gate_sources,
        pi_status as _pi_status,
        pi_tool_targets as _pi_tool_targets,
        render_gate_inventory as _render_pi_gate_inventory,
        render_package as _render_pi_package,
        validate_adapter as _validate_pi_adapter,
    )
except ModuleNotFoundError:
    from tools.pi_agent_surface import (
        PI_MCP_CONFIG,
        PI_PLUGIN_ROOT,
        PI_SKILL_DIRS,
        pi_gate_sources as _pi_gate_sources,
        pi_status as _pi_status,
        pi_tool_targets as _pi_tool_targets,
        render_gate_inventory as _render_pi_gate_inventory,
        render_package as _render_pi_package,
        validate_adapter as _validate_pi_adapter,
    )

try:
    from openspec_projection import projection_targets as _openspec_projection_targets
except ModuleNotFoundError:
    from tools.openspec_projection import projection_targets as _openspec_projection_targets

try:
    import host_surfaces as _host_surfaces
except ModuleNotFoundError:
    from tools import host_surfaces as _host_surfaces


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_MANIFEST = Path("agent-surfaces/manifest.json")
DEFAULT_IDENTITY = Path("agent-surfaces/identity.json")
GENERATED_HEADER = "<!-- Generated by tools/render_agent_surfaces.py; edit agent-surfaces/* instead. -->"
CODEX_PLUGIN_ROOT = Path("plugins/escapement")
CLAUDE_PLUGIN_ROOT = Path("plugins/escapement-claude")
VALID_STATUSES = {"ready", "partial", "unsupported"}
# Every surface ships to every host by default. A host may be left out only by
# an explicit partial/unsupported entry whose reason says why.
ALL_HOSTS = ("claude", "codex", "pi")
ALL_HOSTS_POLICY = (
    "every surface ships to every host by default: declare it ready with "
    "fixtures, or partial/unsupported with an unsupported_reason"
)
MISSION_START = "<!-- escapement:mission:start -->"
MISSION_END = "<!-- escapement:mission:end -->"
CAPABILITIES_START = "<!-- escapement:capabilities:start -->"
CAPABILITIES_END = "<!-- escapement:capabilities:end -->"
ADAPTER_MAPPING_START = "<!-- escapement:adapter-mapping:start -->"
ADAPTER_MAPPING_END = "<!-- escapement:adapter-mapping:end -->"
SHARED_HOOK_SUPPORT = {
    # Token-position-aware reader for `bd <subcommand>` invocations, imported by
    # every bd-triggered gate. Omitting it makes those gates fail silent: they
    # refuse to guess with a substring match, so the gate is inert where it was
    # needed.
    "claude/hooks/_bd_command.py",
    # Resolves which directory a command is about, read by the dispatcher
    # before any gate runs. Omitting it silently restores the old behaviour:
    # every gate judges the session's directory instead of the command's.
    "claude/hooks/_effective_cwd.py",
    "claude/hooks/_worktree_cli.py",
    "claude/hooks/_gate_signal.py",
    "claude/hooks/_advisory_dedupe.py",
    "claude/hooks/_local_judge_client.py",
    "claude/hooks/_gh_command.py",
    # The merge gate's green-status half. Omitting it makes the gate deny every merge
    # (it fails toward denying, never toward a silent allow) in the installed plugin.
    "claude/hooks/_merge_green_status.py",
    # Landing-time gates share repository-neutral origin/HEAD + merge-base
    # authority. Omitting this sibling makes installed hooks fail open.
    "claude/hooks/git_change_scope.py",
    # Reader for Codex's apply_patch payload, imported by every gate that has
    # to work on Codex. Same failure mode: without it the import fails, the
    # gate fails open, and it is inert exactly where it was needed.
    "claude/hooks/_codex_patch.py",
    # One owner for how a hook speaks to a host. A wrong wire shape is silent:
    # the hook fires, decides correctly, and nothing happens.
    "claude/hooks/_host_output.py",
    # Both advisory boundaries use the corpus-backed per-function strength
    # differ; its parser is a required transitive sibling in installed hosts.
    "claude/hooks/oracle_strength_diff.py",
    "claude/hooks/oracle_strength_parse.py",
    # implementation_echo_test_gate imports this policy helper in both hosts.
    # Omitting it makes the defensive import fallback hard-deny fixture echoes.
    "claude/hooks/data_fixture_echo.py",
    # implementation_echo_test_gate imports both analyzers in both hosts.
    # Omitting either silently activates a permissive defensive fallback.
    "claude/hooks/magic_number_echo.py",
    "claude/hooks/oracle_reason_validation.py",
    # test_oracle_brief_gate keeps path/content and landing-command policy in
    # bounded siblings shared byte-for-byte by both host packages.
    "claude/hooks/oracle_brief_rapid.py",
    "claude/hooks/test_oracle_brief_policy.py",
    "claude/hooks/test_oracle_brief_landing.py",
    # Every Serena-aware gate recognizes the bundled server's tool names on
    # every host through this one helper.
    "claude/hooks/_serena_tools.py",
    # Host detection and the captured Codex spawn_agent payload mapping, imported
    # at module scope by every agent-dispatch gate. Omitting it crashes them.
    "claude/hooks/_agent_dispatch.py",
}
SHARED_RUNTIME_SUPPORT = {
    "bin/escapement-worktree",
    "bin/escapement_worktree.py",
    "bin/escapement_worktree_activity.py",
    "bin/escapement_worktree_allocate_ref.py",
    "bin/escapement_worktree_bootstrap.py",
    "bin/escapement_worktree_cleanup.py",
    "bin/escapement_worktree_finish.py",
    "bin/escapement_worktree_git.py",
    "bin/escapement_worktree_github.py",
    "bin/escapement_worktree_registry.py",
    "bin/escapement_worktree_recovery.py",
    "bin/escapement_worktree_rollback_fs.py",
    "bin/escapement_worktree_rollback_lock.py",
    "bin/escapement_worktree_rollback_ref.py",
    "bin/escapement_worktree_root.py",
    # Split out of escapement_worktree_root.py by #247 and imported at module scope by
    # escapement_worktree_git.py:17. Omitting it here does not fail --check (the check
    # validates the targets it knows, not the ones it forgot), it silently PRUNES the
    # module from every plugin tree and breaks the importer at runtime.
    "bin/escapement_worktree_root_health.py",
    # The neutral capability runtime is the policy source for every selected
    # client; host packages only carry these modules as generated copies.
    "harness/bin/neutral_adapters.py",
    "harness/bin/neutral_contract.py",
    "harness/bin/neutral_oracle.py",
    "harness/bin/neutral_registry.py",
    "harness/bin/neutral_runtime.py",
    "harness/bin/neutral_supervisor.py",
    "harness/schemas/neutral-capabilities.json",
}
CODEX_HOOK_SUPPORT = {
    # Codex Bash policy gates execute through one in-process dispatcher to avoid
    # multiplying interpreter startup and filesystem pressure per tool call.
    "claude/hooks/codex_pretool_dispatch.py",
    "claude/hooks/_local_judge_client.py",
    # prepatch_failure_gate.py loads its verifier from <plugin root>/harness/bin.
    # Without it the gate finds no verifier and allows every landing unexamined.
    "harness/bin/prepatch_verify.py",
    # merge_authorization_gate.py resolves this sibling via its plugin-relative
    # path. Without it, an explicitly authorized Codex repository is denied
    # fail-closed because the policy reader cannot be imported.
    "harness/bin/repo_outcome.py",
    # codex_stop_hook.py imports its decision core rather than reimplementing it;
    # verify_integrity.py is would_block_stop's own transitive sibling. Without
    # both, the Stop hook raises ImportError, fails open, and the Codex adapter
    # is inert in exactly the wind-down it was added to catch.
    "harness/bin/would_block_stop.py",
    "harness/bin/verify_integrity.py",
    "harness/bin/schedule_store.py",
    "harness/bin/session_observer.py",
    "harness/bin/continuation_watchdog.py",
    "harness/bin/task_session_mode.py",
    "harness/bin/thread_identity.py",
    "harness/bin/trusted_json.py",
    "harness/bin/trusted_source.py",
    "harness/bin/wakeup_dispatch.py",
    "harness/bin/wakeup_waker.py",
    "harness/bin/winddown_gate.py",
    "harness/bin/winddown_judge.py",
    "harness/bin/worktree_lifecycle_supervisor.py",
    "harness/schemas/contract.schema.json",
    "harness/schemas/executions.schema.json",
    "harness/schemas/scheduled.schema.json",
}
CLAUDE_EXTRA_HOOK_SUPPORT = {
    "claude/hooks/local_judge_health.py",
}

CODEX_FORBIDDEN = (
    "~/.claude",
    "CLAUDE_CODE_SESSION_ID",
    "ScheduleWakeup",
    "TeamCreate",
)
CODEX_SKILL_FORBIDDEN = (
    "TodoWrite",
    "AskUserQuestion",
    "Task tool",
    "subagent_type",
)
MAX_CODEX_HOOK_TIMEOUT_SECONDS = 900
CODEX_DISPATCH_OVERHEAD_SECONDS_PER_GATE = 1


def _load_manifest(path: Path) -> dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8"))


def _load_identity(path: Path) -> dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8"))


def _read_fragment(root: Path, rel: str) -> str:
    path = root / rel
    return path.read_text(encoding="utf-8").strip()


def _render_fragment(root: Path, rel: str, identity: dict[str, Any]) -> str:
    text = _read_fragment(root, rel)
    if rel != "agent-surfaces/onboarding/shared.md":
        return text
    if MISSION_START in text and MISSION_END in text:
        before, remainder = text.split(MISSION_START, 1)
        _current, after = remainder.split(MISSION_END, 1)
        mission = identity.get("mission", "")
        text = f"{before}{MISSION_START}\n{mission}\n{MISSION_END}{after}"
    if CAPABILITIES_START in text and CAPABILITIES_END in text:
        before, remainder = text.split(CAPABILITIES_START, 1)
        _current, after = remainder.split(CAPABILITIES_END, 1)
        capabilities = "\n".join(
            f"{index}. {capability}"
            for index, capability in enumerate(identity.get("capabilities", ()), start=1)
        )
        text = f"{before}{CAPABILITIES_START}\n{capabilities}\n{CAPABILITIES_END}{after}"
    if ADAPTER_MAPPING_START in text and ADAPTER_MAPPING_END in text:
        before, remainder = text.split(ADAPTER_MAPPING_START, 1)
        _current, after = remainder.split(ADAPTER_MAPPING_END, 1)
        mapping = "\n".join(
            f"- {capability} | {', '.join(tools)}"
            for capability, tools in identity.get("current_adapters", {}).items()
        )
        text = f"{before}{ADAPTER_MAPPING_START}\n{mapping}\n{ADAPTER_MAPPING_END}{after}"
    return text


# hosts.<id>.include_shared_fragments defaults True (codex/claude): their
# rendered document is the host's ONLY delivery channel for the shared
# Escapement workflow text, so it must carry the shared fragments in full.
# Pi sets it False: the Pi host (OMP) auto-loads this repository's AGENTS.md
# natively as repo-rules context on every session, so PI.md — injected a
# second time via before_agent_start — only needs the Pi-specific delta.
# Carrying the shared fragments in both would double every Pi session's
# fixed context cost for text already delivered (escapement-w4sn is the
# same principle applied to Claude's disjoint claude/rules/* channel).
def _render_document(
    root: Path,
    manifest: dict[str, Any],
    identity: dict[str, Any],
    host: str,
) -> str:
    docs = manifest["documents"]
    host_doc = docs["hosts"][host]
    parts = [GENERATED_HEADER, "", f"# {host_doc['title']}", ""]
    if host_doc.get("include_shared_fragments", True):
        for rel in docs["shared_fragments"]:
            parts.append(_render_fragment(root, rel, identity))
            parts.append("")
    for rel in host_doc["fragments"]:
        parts.append(_read_fragment(root, rel))
        parts.append("")
    return "\n".join(parts).rstrip() + "\n"


def _render_codex_hooks(manifest: dict[str, Any]) -> str:
    # The installable plugin is the sole Codex hook owner. Keep this generated
    # compatibility surface empty so opening the Escapement repository while the
    # plugin is installed cannot execute every lifecycle hook twice.
    return json.dumps({"hooks": {}}, indent=2, sort_keys=True) + "\n"


def _codex_plugin_command(command: str) -> str:
    for interpreter in ("python3 -B ", "python3 "):
        if not command.startswith(interpreter):
            continue
        tail = command[len(interpreter):]
        if not tail.startswith(("claude/hooks/", "harness/bin/")):
            return command
        script, separator, rest = tail.partition(" ")
        rewritten = f'{interpreter}"${{PLUGIN_ROOT}}/{script}"'
        if separator:
            rewritten += " " + rest
        return rewritten
    return command


def _read_json_or_none(path: Path) -> dict[str, Any] | None:
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except (OSError, ValueError):
        return None


def _codex_group_identity(group: dict[str, Any]) -> tuple[str, str]:
    """A hook group's identity across releases: its matcher and script path,
    not its arguments (the Bash dispatcher's gate list grows)."""
    command = group["hooks"][0]["command"]
    script = command.split('"', 2)[1] if '"' in command else command
    return group.get("matcher", ""), script


def _keep_trusted_positions(
    hooks: dict[str, list[dict[str, Any]]], previous: dict[str, Any] | None
) -> dict[str, list[dict[str, Any]]]:
    """Order each event's groups as the previous release did, new groups last.

    Codex keys hook trust by ``<event>:<group index>:<hook index>`` and hashes
    the definition found there, so inserting a group ahead of others silently
    untrusts every group it displaces. Anchoring on the committed file keeps
    the grants the user already made valid; only new or changed hooks need
    review.
    """
    if not previous:
        return hooks
    ordered: dict[str, list[dict[str, Any]]] = {}
    for event, groups in hooks.items():
        rank = {
            _codex_group_identity(group): index
            for index, group in enumerate(previous.get("hooks", {}).get(event, []))
        }
        ordered[event] = sorted(
            groups, key=lambda group: rank.get(_codex_group_identity(group), len(rank))
        )
    return ordered


def _render_codex_plugin_hooks(manifest: dict[str, Any], previous: dict[str, Any] | None = None) -> str:
    hooks: dict[str, list[dict[str, Any]]] = {}
    bash_sources: list[str] = []
    bash_timeouts: list[int] = []
    for hook in manifest.get("hooks", []):
        host = hook.get("hosts", {}).get("codex", {})
        if host.get("status") != "ready":
            continue
        for event in host.get("events", []):
            if event.get("event") == "PreToolUse" and event.get("matcher") == "Bash":
                bash_sources.append(hook["source"])
                if event.get("timeout_seconds") is not None:
                    bash_timeouts.append(event["timeout_seconds"])

    dispatcher_rendered = False
    for hook in manifest.get("hooks", []):
        host = hook.get("hosts", {}).get("codex", {})
        if host.get("status") != "ready":
            continue
        for event in host.get("events", []):
            if event.get("event") == "PreToolUse" and event.get("matcher") == "Bash":
                if dispatcher_rendered:
                    continue
                command = (
                    'python3 -B "${PLUGIN_ROOT}/claude/hooks/'
                    'codex_pretool_dispatch.py"'
                )
                command += "".join(
                    f" --gate {shlex.quote(source)} --gate-timeout {timeout}"
                    for source, timeout in zip(
                        bash_sources, bash_timeouts, strict=True
                    )
                )
                item = {
                    "matcher": "Bash",
                    "hooks": [{"type": "command", "command": command}],
                }
                if bash_timeouts:
                    item["hooks"][0]["timeout"] = sum(bash_timeouts) + (
                        len(bash_timeouts) * CODEX_DISPATCH_OVERHEAD_SECONDS_PER_GATE
                    )
                hooks.setdefault("PreToolUse", []).append(item)
                dispatcher_rendered = True
                continue
            item: dict[str, Any] = {
                "matcher": event.get("matcher", ""),
                "hooks": [
                    {
                        "type": "command",
                        "command": _codex_plugin_command(event["command"]),
                    }
                ],
            }
            timeout = event.get("timeout_seconds")
            if timeout is not None:
                item["hooks"][0]["timeout"] = timeout
            hooks.setdefault(event["event"], []).append(item)
    hooks = _keep_trusted_positions(hooks, previous)
    return json.dumps({"hooks": hooks}, indent=2, sort_keys=True) + "\n"


MCP_CONFIG_NAME = ".mcp.json"


def _ready_mcp_servers(manifest: dict[str, Any], host: str) -> list[tuple[dict[str, Any], dict[str, Any]]]:
    return [
        (server, server["hosts"][host])
        for server in manifest.get("mcp_servers", [])
        if server.get("hosts", {}).get(host, {}).get("status") == "ready"
    ]


def _render_mcp_config(manifest: dict[str, Any], host: str) -> str:
    """One MCP launch contract per server; hosts differ only in Serena-style
    `--context` and host-specific options (e.g. Codex startup timeout)."""
    servers: dict[str, Any] = {}
    for server, entry in _ready_mcp_servers(manifest, host):
        args = list(server["args"])
        if entry.get("context"):
            args += ["--context", entry["context"]]
        servers[server["id"]] = {
            "command": server["command"],
            "args": args,
            **entry.get("options", {}),
        }
    return json.dumps({"mcpServers": servers}, indent=2) + "\n"


def _render_codex_plugin_manifest(identity: dict[str, Any], manifest: dict[str, Any]) -> str:
    mission = identity["mission"]
    product = identity["product_interface"]
    payload = {
        "name": "escapement",
        "version": "0.1.0",
        "description": mission,
        "author": {
            "name": "alexander-vyh",
            "url": "https://github.com/alexander-vyh",
        },
        "homepage": "https://github.com/alexander-vyh/escapement",
        "repository": "https://github.com/alexander-vyh/escapement",
        "license": "GPL-3.0-or-later",
        "keywords": product["keywords"],
        "skills": "./skills/",
        # Declare hooks explicitly rather than rely on Codex's undocumented default
        # discovery of hooks/hooks.json (escapement-z506). Verified accepted by
        # codex-cli 0.144.1: a plugin declaring `"hooks": "./hooks/hooks.json"`
        # installs cleanly. The embedded plugin-json-spec confirms the key
        # supplements (does not replace) default discovery.
        "hooks": "./hooks/hooks.json",
        # Same shape curated Codex plugins use (e.g. codex-security):
        # a plugin-relative .mcp.json holding an `mcpServers` object.
        **({"mcpServers": f"./{MCP_CONFIG_NAME}"} if _ready_mcp_servers(manifest, "codex") else {}),
        "interface": {
            "displayName": "Escapement",
            "shortDescription": identity["short_description"],
            "longDescription": f"{mission} {product['long_description']}",
            "developerName": "alexander-vyh",
            "category": "Developer Tools",
            "capabilities": identity["capabilities"],
            "websiteURL": "https://github.com/alexander-vyh/escapement",
            "defaultPrompt": product["starter_prompts"],
            "brandColor": "#2D6A4F",
        },
    }
    return json.dumps(payload, indent=2) + "\n"


def _render_codex_marketplace() -> str:
    payload = {
        # Public-install name (escapement-z506). Verified: adding this repo via a
        # git URL (`codex plugin marketplace add https://github.com/alexander-vyh/
        # escapement`) resolves the plugin from its `local` source relative to the
        # cloned marketplace root, and `codex plugin marketplace upgrade escapement`
        # then tracks main — so the install command is `codex plugin add
        # escapement@escapement`, not the dev-only `@escapement-local`.
        "name": "escapement",
        "interface": {
            "displayName": "Escapement",
        },
        "plugins": [
            {
                "name": "escapement",
                "source": {
                    "source": "local",
                    "path": "./plugins/escapement",
                },
                "policy": {
                    "installation": "AVAILABLE",
                    "authentication": "ON_INSTALL",
                },
                "category": "Developer Tools",
            }
        ],
    }
    return json.dumps(payload, indent=2) + "\n"


def _codex_ready_hook_sources(manifest: dict[str, Any]) -> set[str]:
    return {
        hook["source"]
        for hook in manifest.get("hooks", [])
        if hook.get("source") != "bd" and hook.get("hosts", {}).get("codex", {}).get("status") == "ready"
    }


# Deployed-path -> vendored-plugin-path rewrites. Order matters: the more
# specific harness/bin prefix is checked before the generic hooks prefix.
# Args after the script (e.g. `--quiet`) are preserved.
_PLUGIN_PATH_REWRITES = (
    ("~/.claude/harness/bin/", "${CLAUDE_PLUGIN_ROOT}/harness/bin/"),
    ("~/.claude/hooks/", "${CLAUDE_PLUGIN_ROOT}/hooks/"),
)


def _claude_plugin_command(command: str) -> str:
    # Rewrite a deployed ~/.claude/{hooks,harness/bin}/<script> command to its
    # vendored plugin path. Commands outside those managed paths pass through.
    for prefix, repl in _PLUGIN_PATH_REWRITES:
        if prefix in command:
            head, tail = command.split(prefix, 1)
            script, sep, rest = tail.partition(" ")
            rebuilt = f'{head}"{repl}{script}"'
            if sep:
                rebuilt += " " + rest
            return rebuilt
    return command


def _render_claude_plugin_hooks(manifest: dict[str, Any]) -> str:
    hooks: dict[str, list[dict[str, Any]]] = {}
    for hook in manifest.get("hooks", []):
        host = hook.get("hosts", {}).get("claude", {})
        if host.get("status") != "ready":
            continue
        for event in host.get("events", []):
            command = event.get("command")
            if not command:
                continue
            item: dict[str, Any] = {
                "matcher": event.get("matcher", ""),
                "hooks": [
                    {"type": "command", "command": _claude_plugin_command(command)}
                ],
            }
            timeout = event.get("timeout_seconds")
            if timeout is not None:
                item["hooks"][0]["timeout"] = timeout
            hooks.setdefault(event["event"], []).append(item)
    return json.dumps({"hooks": hooks}, indent=2, sort_keys=True) + "\n"


def _render_claude_plugin_manifest(identity: dict[str, Any]) -> str:
    product = identity["product_interface"]
    payload = {
        "$schema": "https://anthropic.com/claude-code/plugin.schema.json",
        "name": "escapement",
        "description": f"{identity['short_description']} {identity['mission']}",
        # NO `version` field — deliberate (escapement-9mki). Claude Code resolves an
        # unversioned plugin's version from the git commit SHA of the git-subdir
        # source, so every commit to main is a new version and `claude plugin update`
        # actually advances the install. A static `version` (e.g. "1.0.0") pins
        # resolution to that literal and makes `claude plugin update` a permanent
        # no-op. Verified 2026-07-10 against a real git-subdir-from-GitHub probe:
        # unversioned install updated 99d69bd->bf09f86 on a new commit; a static
        # version reported "already at latest". Do NOT add a version field back.
        "author": {"name": "alexander-vyh"},
        "repository": "https://github.com/alexander-vyh/escapement",
        "homepage": "https://github.com/alexander-vyh/escapement",
        "license": "GPL-3.0-or-later",
        "keywords": product["keywords"],
    }
    return json.dumps(payload, indent=2) + "\n"


def _render_claude_marketplace(identity: dict[str, Any]) -> str:
    payload = {
        "$schema": "https://anthropic.com/claude-code/marketplace.schema.json",
        "name": "escapement",
        "description": f"{identity['short_description']} {identity['mission']}",
        "owner": {"name": "alexander-vyh"},
        "plugins": [
            {
                "name": "escapement",
                "description": (
                    f"{identity['short_description']} {identity['mission']} "
                    "Always-on rules are injected via a "
                    "SessionStart hook. Unversioned, so `claude "
                    "plugin update escapement@escapement` tracks main automatically; "
                    "scripts/plugin-update.sh forces a refresh and also preserves "
                    "your model key and prunes duplicate hook registrations."
                ),
                "source": {
                    "source": "git-subdir",
                    "url": "https://github.com/alexander-vyh/escapement",
                    "path": "plugins/escapement-claude",
                    "ref": "main",
                },
                "category": "development",
                "author": {"name": "alexander-vyh"},
                "homepage": "https://github.com/alexander-vyh/escapement",
            }
        ],
    }
    return json.dumps(payload, indent=2) + "\n"


def _claude_ready_hook_sources(manifest: dict[str, Any]) -> set[str]:
    return {
        hook["source"]
        for hook in manifest.get("hooks", [])
        if hook.get("source") != "bd"
        and hook.get("hosts", {}).get("claude", {}).get("status") == "ready"
    }


def rendered_targets(
    root: Path,
    manifest: dict[str, Any],
    identity: dict[str, Any] | None = None,
) -> dict[Path, str]:
    if identity is None:
        identity = _load_identity(root / DEFAULT_IDENTITY)
    docs = manifest["documents"]["hosts"]
    targets = {
        root / docs["codex"]["target"]: _render_document(root, manifest, identity, "codex"),
        root / docs["claude"]["target"]: _render_document(root, manifest, identity, "claude"),
        root / docs["pi"]["target"]: _render_document(root, manifest, identity, "pi"),
        root / "package.json": _render_pi_package(identity),
        root / PI_PLUGIN_ROOT / "gates.json": _render_pi_gate_inventory(manifest),
        # Every module of the Pi extension: index.ts is the entry package.json
        # names, and it imports its siblings relatively.
        **{
            root / PI_PLUGIN_ROOT / "extensions" / module.name: module.read_text(encoding="utf-8")
            for module in sorted((root / "agent-surfaces" / "hosts" / "pi" / "extensions").glob("*.ts"))
        },
        root / ".codex" / "hooks.json": _render_codex_hooks(manifest),
        root / ".agents" / "plugins" / "marketplace.json": _render_codex_marketplace(),
        root / CODEX_PLUGIN_ROOT / ".codex-plugin" / "plugin.json": _render_codex_plugin_manifest(identity, manifest),
        root / CODEX_PLUGIN_ROOT / "hooks" / "hooks.json": _render_codex_plugin_hooks(
            manifest, _read_json_or_none(root / CODEX_PLUGIN_ROOT / "hooks" / "hooks.json")
        ),
        # Escapement-owned MCP servers, one file per host package.
        root / CODEX_PLUGIN_ROOT / MCP_CONFIG_NAME: _render_mcp_config(manifest, "codex"),
        root / CLAUDE_PLUGIN_ROOT / MCP_CONFIG_NAME: _render_mcp_config(manifest, "claude"),
        root / PI_PLUGIN_ROOT / PI_MCP_CONFIG: _render_mcp_config(manifest, "pi"),
    }

    # Canon-projected surfaces (agent-surfaces/openspec/<op>.md, agent-surfaces/
    # skills/<id>.md) are the single authoring source for ops/skills with a
    # per-host content variance; project them into their host surfaces FIRST so
    # the vendoring loops below vendor the freshly-projected bytes rather than a
    # stale on-disk read of the very file this projection also writes (the
    # canon/host data-flow-inversion this topology avoids: canon is read-only
    # input, .agents/skills/*/SKILL.md, claude/skills/*/SKILL.md, and
    # .claude/commands/opsx/*.md are write-only outputs, never both).
    openspec_surfaces: dict[Path, str] = {}
    for canon_dir in CANON_DIRS:
        openspec_surfaces.update(_openspec_projection_targets(root, canon_dir=Path(canon_dir)))
    targets.update(openspec_surfaces)

    def skill_files(skills_root: Path) -> list[Path]:
        # On-disk skills plus freshly projected ones, so a new canon skill is
        # vendored on its first render instead of drifting until the second.
        found = set(skills_root.glob("*/SKILL.md"))
        found.update(
            path for path in openspec_surfaces
            if path.name == "SKILL.md" and path.parent.parent == skills_root
        )
        return sorted(found)

    for skill_path in skill_files(root / ".agents" / "skills"):
        rel = skill_path.relative_to(root / ".agents")
        content = openspec_surfaces.get(skill_path, None)
        if content is None:
            content = skill_path.read_text(encoding="utf-8")
        targets[root / CODEX_PLUGIN_ROOT / rel] = content
        for sibling in sorted(skill_path.parent.rglob("*")):
            if sibling.is_file() and sibling != skill_path:
                sib_rel = sibling.relative_to(root / ".agents")
                targets[root / CODEX_PLUGIN_ROOT / sib_rel] = sibling.read_text(encoding="utf-8")

    for source in sorted(SHARED_RUNTIME_SUPPORT):
        content = (root / source).read_text(encoding="utf-8")
        targets[root / CODEX_PLUGIN_ROOT / source] = content
        targets[root / CLAUDE_PLUGIN_ROOT / source] = content
        targets[root / PI_PLUGIN_ROOT / source] = content

    hook_sources = _codex_ready_hook_sources(manifest)
    if hook_sources:
        hook_sources.update(SHARED_HOOK_SUPPORT)
    for source in sorted(hook_sources):
        source_path = root / source
        if source_path.exists():
            targets[root / CODEX_PLUGIN_ROOT / source] = source_path.read_text(encoding="utf-8")
    for source in sorted(CODEX_HOOK_SUPPORT):
        source_path = root / source
        if source_path.exists():
            targets[root / CODEX_PLUGIN_ROOT / source] = source_path.read_text(encoding="utf-8")

    # Every Pi gate and every sibling module it imports. gates.json names a
    # gate by path and the dispatcher opens it from the plugin root, so a gate
    # listed but not vendored is a gate that cannot run -- the inventory looks
    # right and the brake is not there.
    for source in sorted(_pi_gate_sources(manifest, root, SHARED_HOOK_SUPPORT)):
        source_path = root / source
        if source_path.exists():
            targets[root / PI_PLUGIN_ROOT / source] = source_path.read_text(encoding="utf-8")

    # --- Claude plugin tree (plugins/escapement-claude) + root marketplace ---
    targets[root / ".claude-plugin" / "marketplace.json"] = _render_claude_marketplace(identity)
    targets[root / CLAUDE_PLUGIN_ROOT / ".claude-plugin" / "plugin.json"] = _render_claude_plugin_manifest(identity)
    targets[root / CLAUDE_PLUGIN_ROOT / "hooks" / "hooks.json"] = _render_claude_plugin_hooks(manifest)

    # Rules, commands and agents for every ready host (tools/host_surfaces.py).
    targets.update(_host_surfaces.render_targets(root, manifest, openspec_surfaces))

    # Vendor Claude skills at the plugin's default location.
    for skill_path in skill_files(root / "claude" / "skills"):
        rel = skill_path.relative_to(root / "claude")
        content = openspec_surfaces.get(skill_path, None)
        if content is None:
            content = skill_path.read_text(encoding="utf-8")
        targets[root / CLAUDE_PLUGIN_ROOT / rel] = content
        if skill_path.parent.is_dir():
            for sibling in sorted(skill_path.parent.rglob("*")):
                if sibling.is_file() and sibling != skill_path:
                    sib_rel = sibling.relative_to(root / "claude")
                    targets[root / CLAUDE_PLUGIN_ROOT / sib_rel] = sibling.read_text(encoding="utf-8")

    # Vendor Claude-ready hook sources into hooks/ (flat) plus the shared
    # _gate_signal helper, so a hook's `from _gate_signal import record` resolves.
    claude_hook_sources = _claude_ready_hook_sources(manifest)
    if claude_hook_sources:
        claude_hook_sources.update(SHARED_HOOK_SUPPORT | CLAUDE_EXTRA_HOOK_SUPPORT)
    for source in sorted(claude_hook_sources):
        # harness/* sources are vendored wholesale into harness/ below, not flat into hooks/.
        if source.startswith("harness/"):
            continue
        source_path = root / source
        if source_path.exists():
            targets[root / CLAUDE_PLUGIN_ROOT / "hooks" / Path(source).name] = source_path.read_text(encoding="utf-8")

    # Bundle the continuation-harness (bin + schemas) so its hooks run from the
    # plugin via ${CLAUDE_PLUGIN_ROOT}/harness/bin. Runtime STATE still resolves to
    # ~/.claude/harness (DEFAULT_HARNESS_ROOT), independent of this read-only code.
    for sub in ("bin", "schemas"):
        src_dir = root / "harness" / sub
        for hpath in sorted(src_dir.glob("*")):
            if hpath.is_file():
                targets[root / CLAUDE_PLUGIN_ROOT / "harness" / sub / hpath.name] = \
                    hpath.read_text(encoding="utf-8")

    return targets


def _is_within(path: Path, parent: Path) -> bool:
    try:
        path.relative_to(parent)
    except ValueError:
        return False
    return True


def _publication_units(root: Path, targets: dict[Path, str]) -> tuple[Path, ...]:
    """Return atomic replacement units for generated files and complete plugin trees."""

    managed_roots = (CODEX_PLUGIN_ROOT, CLAUDE_PLUGIN_ROOT, PI_PLUGIN_ROOT)
    units = {Path(".codex-plugin"), *managed_roots}
    for target in targets:
        relative = target.relative_to(root)
        if not any(_is_within(relative, managed_root) for managed_root in managed_roots):
            units.add(relative)
    return tuple(sorted(units, key=lambda path: (len(path.parts), path.as_posix())))


def _stage_targets(root: Path, targets: dict[Path, str], prepared: Path) -> None:
    """Write the complete next generation without modifying any published surface."""

    for path, content in targets.items():
        staged = prepared / path.relative_to(root)
        staged.parent.mkdir(parents=True, exist_ok=True)
        staged.write_text(content, encoding="utf-8")
        if staged.name == "escapement-worktree" and staged.parent.name == "bin":
            staged.chmod(0o755)


def _remove_published_path(path: Path) -> None:
    if path.is_dir() and not path.is_symlink():
        shutil.rmtree(path)
    elif path.exists() or path.is_symlink():
        path.unlink()


def _publish_staged(root: Path, prepared: Path, backup: Path, units: tuple[Path, ...]) -> None:
    """Publish all staged units transactionally, restoring old state on any failure."""

    states: list[tuple[Path, Path, bool]] = []
    try:
        for relative in units:
            destination = root / relative
            staged = prepared / relative
            saved = backup / relative
            had_existing = destination.exists() or destination.is_symlink()
            if had_existing:
                saved.parent.mkdir(parents=True, exist_ok=True)
                os.replace(destination, saved)
            states.append((destination, saved, had_existing))
            if staged.exists() or staged.is_symlink():
                destination.parent.mkdir(parents=True, exist_ok=True)
                os.replace(staged, destination)
    except OSError as publish_error:
        rollback_errors: list[str] = []
        for destination, saved, had_existing in reversed(states):
            try:
                _remove_published_path(destination)
                if had_existing:
                    destination.parent.mkdir(parents=True, exist_ok=True)
                    os.replace(saved, destination)
            except OSError as rollback_error:
                rollback_errors.append(f"{destination}: {rollback_error}")
        if rollback_errors:
            detail = "; ".join(rollback_errors)
            raise OSError(f"publish failed ({publish_error}); rollback incomplete: {detail}") from publish_error
        raise


def _validate_host_entry(kind: str, item_id: str, host: str, entry: dict[str, Any], errors: list[str]) -> None:
    status = entry.get("status")
    if status not in VALID_STATUSES:
        errors.append(f"{kind} {item_id}: host {host} has invalid status {status!r}")
        return
    if status == "ready":
        if kind == "hook" and not entry.get("fixtures"):
            errors.append(f"hook {item_id}: host {host} ready without fixtures")
        if not entry.get("events") and kind == "hook":
            errors.append(f"hook {item_id}: host {host} ready without events")
    if status in {"partial", "unsupported"} and not entry.get("unsupported_reason"):
        errors.append(f"{kind} {item_id}: host {host} {status} without unsupported_reason")


def _validate_fixture(root: Path, kind: str, item_id: str, host: str, fixture: str, errors: list[str]) -> None:
    path_text, _, selector = fixture.partition("::")
    path = root / path_text
    if kind == "hook" and host == "codex":
        if not selector or path.suffix != ".py":
            errors.append(f"{kind} {item_id}: host {host} Codex hook fixture must be a pytest selector: {fixture}")
        elif "codex" not in selector.lower():
            errors.append(f"{kind} {item_id}: host {host} Codex hook fixture must be Codex-specific: {fixture}")
    if not path.exists():
        errors.append(f"{kind} {item_id}: host {host} fixture does not exist: {fixture}")
        return
    if selector:
        text = path.read_text(encoding="utf-8", errors="replace")
        selector_name = selector.split("[", 1)[0]
        if f"def {selector_name}(" not in text and f"class {selector_name}" not in text:
            errors.append(f"{kind} {item_id}: host {host} fixture selector not found: {fixture}")


def _fixture_matches_hook_source(root: Path, fixture: str, source: str, item_id: str) -> bool:
    path_text, _, _selector = fixture.partition("::")
    fixture_path = root / path_text
    if not fixture_path.is_file():
        return False
    fixture_text = fixture_path.read_text(encoding="utf-8", errors="replace")
    normalized_fixture = fixture_text.lower().replace("-", "_")
    source_stem = Path(source).stem.lower().replace("-", "_")
    hook_id = item_id.lower().replace("-", "_")
    return source_stem in normalized_fixture or hook_id in normalized_fixture


def _frontmatter(text: str) -> dict[str, str] | None:
    lines = text.splitlines()
    if not lines or lines[0].strip() != "---":
        return None
    values: dict[str, str] = {}
    for line in lines[1:]:
        if line.strip() == "---":
            return values
        if ":" not in line or line.startswith(" "):
            continue
        key, value = line.split(":", 1)
        values[key.strip()] = value.strip().strip('"')
    return None


CANON_DIRS = ("agent-surfaces/openspec", "agent-surfaces/skills", "agent-surfaces/commands", "agent-surfaces/rules")


def _projected_surfaces(root: Path) -> dict[str, str]:
    """Canon projections by repo-relative path: what a render will write."""
    projected: dict[str, str] = {}
    for canon_dir in CANON_DIRS:
        for path, content in _openspec_projection_targets(root, canon_dir=Path(canon_dir)).items():
            projected[path.relative_to(root).as_posix()] = content
    return projected


def _validate_codex_skill(
    root: Path, skill: dict[str, Any], errors: list[str], projected: dict[str, str]
) -> None:
    item_id = skill.get("id", "<missing>")
    target = skill.get("target")
    if not target:
        errors.append(f"skill {item_id}: missing target")
        return
    # Judge the file on disk; a canon skill not yet rendered is judged by the
    # text the render will write.
    path = root / target
    if path.exists():
        text = path.read_text(encoding="utf-8", errors="replace")
    elif target in projected:
        text = projected[target]
    else:
        errors.append(f"skill {item_id}: target missing: {target}")
        return
    if len(text.strip()) < 200:
        errors.append(f"skill {item_id}: Codex skill is empty or too small")

    frontmatter = _frontmatter(text)
    if frontmatter is None:
        errors.append(f"skill {item_id}: Codex skill missing YAML frontmatter")
    else:
        if frontmatter.get("name") != item_id:
            errors.append(f"skill {item_id}: frontmatter name does not match id")
        if not frontmatter.get("description"):
            errors.append(f"skill {item_id}: frontmatter missing description")

    lowered = text.lower()
    if item_id.startswith("openspec-") and "openspec" not in lowered:
        errors.append(f"skill {item_id}: Codex skill lacks OpenSpec workflow content")
    for token in CODEX_SKILL_FORBIDDEN:
        if token in text:
            errors.append(f"skill {item_id}: Codex skill references unavailable tool token: {token}")
    for token in CODEX_FORBIDDEN:
        if token in text:
            errors.append(f"skill {item_id}: Codex skill contains forbidden Claude-only token: {token}")


def validate_manifest(root: Path, manifest: dict[str, Any]) -> list[str]:
    errors: list[str] = []
    for host in ("codex", "claude", "pi"):
        if host not in manifest.get("documents", {}).get("hosts", {}):
            errors.append(f"documents missing host {host}")

    errors.extend(_validate_pi_adapter(manifest))

    for hook in manifest.get("hooks", []):
        item_id = hook.get("id", "<missing>")
        hosts = hook.get("hosts", {})
        for host in ("codex", "claude"):
            if host not in hosts:
                errors.append(f"hook {item_id}: missing host {host}")
                continue
            _validate_host_entry("hook", item_id, host, hosts[host], errors)
            for fixture in hosts[host].get("fixtures", []):
                _validate_fixture(root, "hook", item_id, host, fixture, errors)
        if "pi" in hosts:
            _validate_host_entry("hook", item_id, "pi", hosts["pi"], errors)
            for fixture in hosts["pi"].get("fixtures", []):
                _validate_fixture(root, "hook", item_id, "pi", fixture, errors)
            _validate_pi_events(root, manifest, hook, errors)
        elif _pi_status(manifest, hook) is None:
            errors.append(f"hook {item_id}: missing host pi ({ALL_HOSTS_POLICY})")
        codex = hosts.get("codex", {})
        if codex.get("status") == "ready":
            source = hook.get("source")
            if source and source != "bd" and Path(source).suffix == ".py":
                fixtures = codex.get("fixtures", [])
                if not any(
                    _fixture_matches_hook_source(root, fixture, source, item_id)
                    for fixture in fixtures
                ):
                    errors.append(f"hook {item_id}: Codex hook fixture must match hook source: {source}")
            for event in codex.get("events", []):
                command = event.get("command", "")
                if "timeout" in event:
                    errors.append(f"hook {item_id}: Codex event must use timeout_seconds, not timeout")
                timeout = event.get("timeout_seconds")
                if timeout is not None:
                    if not isinstance(timeout, int) or timeout <= 0:
                        errors.append(f"hook {item_id}: Codex timeout_seconds must be a positive integer")
                    elif timeout > MAX_CODEX_HOOK_TIMEOUT_SECONDS:
                        errors.append(
                            f"hook {item_id}: Codex timeout_seconds exceeds "
                            f"{MAX_CODEX_HOOK_TIMEOUT_SECONDS}: {timeout}"
                        )
                if "~/.claude" in command:
                    errors.append(f"hook {item_id}: Codex command uses ~/.claude")
                if not command:
                    errors.append(f"hook {item_id}: Codex event missing command")
                source = hook.get("source")
                if source and source != "bd" and not (root / source).exists():
                    errors.append(f"hook {item_id}: source does not exist: {source}")

    projected = _projected_surfaces(root)
    manifest_skill_targets = {skill.get("target") for skill in manifest.get("skills", [])}
    actual_skill_targets = {
        path.relative_to(root).as_posix()
        for path in sorted((root / ".agents" / "skills").glob("*/SKILL.md"))
    } | {
        target for target in projected
        if target.startswith(".agents/skills/") and target.endswith("/SKILL.md")
    }
    missing_from_manifest = actual_skill_targets - manifest_skill_targets
    extra_in_manifest = {target for target in manifest_skill_targets if target} - actual_skill_targets
    for target in sorted(missing_from_manifest):
        errors.append(f"skill target not listed in manifest: {target}")
    for target in sorted(extra_in_manifest):
        errors.append(f"manifest skill target missing from workspace: {target}")

    for skill in manifest.get("skills", []):
        item_id = skill.get("id", "<missing>")
        hosts = skill.get("hosts", {})
        for host in ALL_HOSTS:
            if host not in hosts:
                errors.append(f"skill {item_id}: missing host {host} ({ALL_HOSTS_POLICY})")
                continue
            _validate_host_entry("skill", item_id, host, hosts[host], errors)
            counterpart = hosts[host].get("counterpart")
            if counterpart and not (root / counterpart).exists():
                errors.append(f"skill {item_id}: host {host} counterpart does not exist: {counterpart}")
        if hosts.get("codex", {}).get("status") == "ready":
            _validate_codex_skill(root, skill, errors, projected)
        if hosts.get("pi", {}).get("status") == "ready":
            target = skill.get("target") or ""
            if not any(target.startswith(f"{Path(entry).as_posix()}/") for entry in PI_SKILL_DIRS):
                errors.append(f"skill {item_id}: Pi-ready skill target is outside package pi.skills: {target}")

    for server in manifest.get("mcp_servers", []):
        item_id = server.get("id", "<missing>")
        if not server.get("command") or not isinstance(server.get("args"), list):
            errors.append(f"mcp server {item_id}: missing command or args")
        hosts = server.get("hosts", {})
        for host in ALL_HOSTS:
            if host not in hosts:
                errors.append(f"mcp server {item_id}: missing host {host} ({ALL_HOSTS_POLICY})")
                continue
            _validate_host_entry("mcp server", item_id, host, hosts[host], errors)
            if hosts[host].get("status") == "ready" and not hosts[host].get("fixtures"):
                errors.append(f"mcp server {item_id}: host {host} ready without fixtures")
            for fixture in hosts[host].get("fixtures", []):
                _validate_fixture(root, "mcp server", item_id, host, fixture, errors)

    return errors


def _validate_pi_events(root: Path, manifest: dict[str, Any], hook: dict[str, Any], errors: list[str]) -> None:
    """A Pi event the extension does not translate is a gate that never runs,
    and a Pi gate whose file is absent is a gate the package cannot carry."""
    item_id = hook.get("id", "<missing>")
    entry = hook.get("hosts", {}).get("pi", {})
    adapter = manifest.get("adapters", {}).get("pi", {})
    try:
        tool_targets = set(_pi_tool_targets(adapter))
    except KeyError:
        tool_targets = set()  # validate_adapter reports the broken mapping
    tool_events = (adapter.get("source_event"), adapter.get("post_tool_source_event"))
    whole_events = (
        adapter.get("context_source_event"),
        adapter.get("session_source_event"),
        adapter.get("stop_source_event"),
    )
    for event in entry.get("events", []):
        name, matcher = event.get("event"), event.get("matcher")
        if name in tool_events:
            if matcher not in tool_targets:
                errors.append(f"hook {item_id}: Pi {name} matcher {matcher!r} is not a translated Pi tool")
        elif name not in whole_events:
            errors.append(f"hook {item_id}: Pi event {name!r} is not translated by the Pi adapter")
        timeout = event.get("timeout_seconds")
        if not isinstance(timeout, int) or timeout <= 0:
            errors.append(f"hook {item_id}: Pi event needs a positive integer timeout_seconds")
    source = entry.get("source") or hook.get("source")
    if entry.get("status") == "ready" and source and not (root / source).is_file():
        errors.append(f"hook {item_id}: Pi gate source does not exist, so the Pi package cannot carry it: {source}")


def validate_codex_surfaces(targets: dict[Path, str], manifest: dict[str, Any]) -> list[str]:
    errors: list[str] = []
    codex_text = targets[next(path for path in targets if path.name == "AGENTS.md")]
    codex_hooks = targets[next(path for path in targets if path.as_posix().endswith(".codex/hooks.json"))]
    plugin_hooks = targets[next(path for path in targets if path.as_posix().endswith("plugins/escapement/hooks/hooks.json"))]
    for needle in CODEX_FORBIDDEN:
        if needle in codex_text or needle in codex_hooks or needle in plugin_hooks:
            errors.append(f"Codex surface contains forbidden Claude-only token: {needle}")
    if "${CLAUDE_PLUGIN_ROOT}" in plugin_hooks:
        errors.append("Codex plugin hooks must not use CLAUDE_PLUGIN_ROOT")

    repo_hooks = json.loads(codex_hooks)["hooks"]
    if repo_hooks:
        errors.append(
            "repo-local Codex hooks must be empty because the plugin is the sole hook owner"
        )

    plugin_commands = [
        hook["command"]
        for event_items in json.loads(plugin_hooks)["hooks"].values()
        for item in event_items
        for hook in item["hooks"]
    ]
    if any("bd prime" in command for command in plugin_commands):
        errors.append("Codex hooks must not delegate workflow policy to bd prime")
    if not any("escapement_session_context.py" in command for command in plugin_commands):
        errors.append("Codex plugin hooks must include Escapement-owned session context")
    if not any("gate.py" in command for command in plugin_commands):
        errors.append(
            "Codex plugin hooks must include at least one behavioral gate beyond session context"
        )

    for required in (
        "test_oracle_brief_gate.py",
        "implementation_echo_test_gate.py",
        "oracle_downgrade_warning_gate.py",
    ):
        if not any(required in command for command in plugin_commands):
            errors.append(f"Codex plugin hooks must include {required}")
    return errors


def validate_host_surfaces(root: Path, manifest: dict[str, Any], targets: dict[Path, str]) -> list[str]:
    """Rules, commands and agents obey the all-hosts policy (tools/host_surfaces.py)."""
    return _host_surfaces.validate(
        root, manifest, targets, ALL_HOSTS, ALL_HOSTS_POLICY, _validate_host_entry
    )


def check(root: Path, manifest_path: Path) -> int:
    manifest = _load_manifest(manifest_path)
    identity = _load_identity(root / DEFAULT_IDENTITY)
    targets = rendered_targets(root, manifest, identity)
    errors = validate_manifest(root, manifest)
    errors.extend(validate_identity_surfaces(root, manifest, identity))
    errors.extend(validate_codex_surfaces(targets, manifest))
    errors.extend(validate_host_surfaces(root, manifest, targets))

    for path, expected in targets.items():
        if not path.exists():
            errors.append(f"generated target missing: {path.relative_to(root)}")
            continue
        actual = path.read_text(encoding="utf-8")
        if actual != expected:
            errors.append(f"generated target drift: {path.relative_to(root)}")

    if errors:
        for error in errors:
            print(error, file=sys.stderr)
        return 1
    return 0


def render(root: Path, manifest_path: Path) -> int:
    manifest = _load_manifest(manifest_path)
    identity = _load_identity(root / DEFAULT_IDENTITY)
    errors = validate_manifest(root, manifest)
    errors.extend(validate_canonical_identity(identity))
    errors.extend(validate_support_manifest(manifest))
    if errors:
        for error in errors:
            print(error, file=sys.stderr)
        return 1

    targets = rendered_targets(root, manifest, identity)
    overrides = {path.relative_to(root): content for path, content in targets.items()}
    errors = validate_identity_surfaces(root, manifest, identity, overrides)
    errors.extend(validate_codex_surfaces(targets, manifest))
    errors.extend(validate_host_surfaces(root, manifest, targets))
    if errors:
        for error in errors:
            print(error, file=sys.stderr)
        return 1

    try:
        with tempfile.TemporaryDirectory(prefix=".agent-surface-stage-", dir=root) as temporary:
            transaction = Path(temporary)
            prepared = transaction / "prepared"
            backup = transaction / "backup"
            _stage_targets(root, targets, prepared)
            _publish_staged(root, prepared, backup, _publication_units(root, targets))
    except OSError as error:
        print(f"agent surface publication failed: {error}", file=sys.stderr)
        return 1
    return 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail if generated files drift")
    parser.add_argument("--manifest", default=str(DEFAULT_MANIFEST))
    parser.add_argument("--root", default=".")
    args = parser.parse_args(argv)

    root = Path(args.root).resolve()
    manifest_path = Path(args.manifest)
    if not manifest_path.is_absolute():
        manifest_path = root / manifest_path
    if args.check:
        return check(root, manifest_path)
    return render(root, manifest_path)


if __name__ == "__main__":
    raise SystemExit(main())
